### ISSUE TITLE
Question: Exposing merchant id - good or bad?

### ISSUE THREAD

**Issue by prasadh13** [braintree/braintree_node#100]
I am creating a payment gateway using braintree API and wanted to display the braintree badge on the gateway. 
I got [this](https://www.braintreepayments.com/badge) link and was wondering if exposing merchant id is a security concern? I know it is similar to something like google analytics id. But I want to be sure before proceeding.

TIA!

**Comment by crookedneighbor** [comment]
It is not a security concern. The Merchant's public id is used in client side calls to the Braintree gateway, so it is viewable to anyone who has their network panel open while using a Braintree client SDK.
