### ISSUE TITLE
Maestro test Card number doesn't work

### ISSUE THREAD

**Issue by imajus** [braintree/braintree_node#106]
* SDK/Library version: 2.0.2
* Environment: Sandbox
* Language, language version, and OS: Node v4.7.3, Mac OS X/Ubuntu

Many different test Card numbers I've tried worked just fine in Sandbox but when I try Maestro test Card number, I get the error: "payment_method_nonce does not contain a valid payment instrument type."
It seems the same happens in Production, as we've started the investigation based on one of our clients bug report. He is getting the same error when trying to pay, presumably using his Maestro Card.
Not sure if it's a right place to add the issue. If it is not, let me know where I should move it.

The data I've used for testing:
```
Card Number: 6304000000000000
CVV: 123
Expiration: 10/20
```

**Comment by crookedneighbor** [comment]
What's your public merchant id? I suspect your processing is not set up to use maestro cards.

**Comment by imajus** [comment]
It's `majus`.

**Comment by imajus** [comment]
Or is this my Merchant ID: `jwcpqp4hcvgjxq55`?

**Comment by crookedneighbor** [comment]
I've enabled Maestro cards on your sandbox account. However, keep in mind, that depending on how you are onboarded for your production account, you may not be able to process Maestro cards, as their availability for processing is limited by currency and location.

**Comment by imajus** [comment]
@crookedneighbor Can you enable it for Production account as well? The Merchant ID is `dzwnspprskyyvtm3`.

**Comment by crookedneighbor** [comment]
No. I cannot. Please contact our support team to see if you are eligible to process Maestro. https://developers.braintreepayments.com/forms/contact

**Comment by imajus** [comment]
Ok, thanks. I will mask the ID in my previous message just in case.

**Comment by crookedneighbor** [comment]
That's your public id, so there is no security concern.

**Comment by lalit-panda** [comment]
Hi is there any way to active maestro card in my sandbox account.My merchant id is qpw7y67g9v7xtdb3

**Comment by crookedneighbor** [comment]
@lalit-panda  Contact our support team for assistance: https://help.braintreepayments.com/
