### ISSUE TITLE
Sub-merchant account creation is not working properly

### ISSUE THREAD

**Issue by nanofaroque** [braintree/braintree_node#107]
### General information

* SDK/Library version: ^2.2.0
* Environment: Is this issue in Sandbox
* Language, language version, and OS: Node

### Issue description
Sub-merchant is created successfully but when i try to get more informations from the web hook, it showed undefined. Here is my code look like: 

```js
router.post('/', function (req, res, next) {
    gateway.getGateway().webhookNotification.parse(
        req.body.bt_signature,
        req.body.bt_payload,
        function (err, webhookNotification) {
            console.log("[Webhook Received " + webhookNotification.timestamp + "] | Kind: " + webhookNotification.kind);
            console.log('id: '+  webhookNotification.merchantAccount.id);
        }
    );
    res.status(200).send();

});
```

id:undefined. It means it does not have merchantAccount information. Thanks

**Comment by nanofaroque** [comment]
After few try,
                     What i found that JSON structure is completely different than their documentation. Finally I was able to parse it. Here is response look like: 

{"kind": [
    "sub_merchant_account_approved"
  ],
  "timestamp": [
    {
      "_": "2017-07-21T15:52:13Z",
      "$": {
        "type": "datetime"
      }
    }
  ],
  "subject": [
    {
      "merchantAccount": [
        {
          "status": [
            "active"
          ],
          "id": [
            "254687215246101"
          ],
          "masterMerchantAccount": [
            {
              "status": [
                "active"
              ],
              "id": [
                "respayinc"
              ],
              "currencyIsoCode": [
                "USD"
              ],
              "default": [
                {
                  "_": "true",
                  "$": {
                    "type": "boolean"
                  }
                }
              ],
              "subMerchantAccount": [
                {
                  "_": "false",
                  "$": {
                    "type": "boolean"
                  }
                }
              ]
            }
          ],
          "currencyIsoCode": [
            "USD"
          ],
          "default": [
            {
              "_": "false",
              "$": {
                "type": "boolean"
              }
            }
          ],
          "subMerchantAccount": [
            {
              "_": "true",
              "$": {
                "type": "boolean"
              }
            }
          ]
        }
      ]
    }
  ]
}

There is no way to parse this if you follow their documentation from https://developers.braintreepayments.com/guides/braintree-marketplace/confirmation/node

**Comment by NickTomlin** [comment]
Interesting, that payload definitely does not match up with our node documentation. Thanks for bringing this up! 

I'll work with our marketplace team to investigate this.
