### ISSUE TITLE
Error when attempting to find a customer with a numeric ID

### ISSUE THREAD

**Issue by developius** [braintree/braintree_node#108]
### General information

* SDK/Library version: 2.2.0
* Environment: Sandbox
* Language, language version, and OS: Node v8.1.4 on macOS 10.12.5 
### Issue description

When attempting to use `gateway.customer.find(customerID)` with a _numeric_ customerID, this error is thrown (truncated):

```
TypeError: customerId.trim is not a function
at node_modules/braintree/lib/braintree/customer_gateway.js:25:20
```

However, if I call `.toString()` on the number being passed in:

```js
gateway.customer.find(customerID.toString())
```

...it works perfectly. The fix for a user, of course, is to just pass in a string, but I think this is slightly counter-intuitive considering the API returns an actual number when auto-generating an ID for a customer. It would be great if the `customer_gateway.js` only called `.trim()` if the input was a string.

**Comment by NickTomlin** [comment]
Thanks for bringing this up; I agree that the lack of parallelism between input and the returned id is confusing. 

I'll discuss this with our clients team but I don't see any harm in coercing this to a string.

**Comment by NickTomlin** [comment]
I'm actually seeing the type of the `id` on a customer response as a string 

```javascript
return gateway.customer.create({firstName: 'John', lastName: 'Smith'}, function (err, response) {
  let customerId = response.customer.id
  console.log(customerId, typeof customerId) // 8962605738 string
});
```

Can you share how you are making the call the returns a `id` that is a `number`?

**Comment by developius** [comment]
Thanks for getting back to me. It looks like I'm ending up with a number because I'm using a Mongoose schema for my user data, which requires the Braintree customer ID to be a number, so that's where the number is coming from. Regardless, I think coercing would be a useful change.

**Comment by jaypatel512** [comment]
Considering the response contains `id` as a string, allowing multiple input types and intelligently trying to convert to compatible type could lead to bad integrations in future. The classic example would be introducing `alphanumeric` values for `customerId`. This breaks integrations, and will cause trouble for a lot. Having a consistent type expectations makes it easier to follow the code, as well as easier for us to make changes in future, without breaking integrations.
