### ISSUE TITLE
[Help] Validating if payment method(card) already exists

### ISSUE THREAD

**Issue by d30jeff** [braintree/braintree_node#109]
### General information

* SDK/Library version: 2.2.0
* Environment: Sandbox
* Language, language version, and OS: Node v.8.1.4 on MacOS Sierra 10.12.6

### Issue description

We are storing the payment method token in our database.
I'm trying to check if a customer tries to add an already existing card.

But it [appears](https://developers.braintreepayments.com/guides/payment-methods/node#find) that the `paymentMethod.find()` method only accepts `token`  as its parameter.

  - which in my understanding, is part of the `paymentMethod` object. ie. after creating

I was wondering if there's another way to `.find` a payment method with a different param.

Anyway,

My most recent attempt is to use the `failOnDuplicatePaymentMethod` when creating a payment.
But looking at #57, I realized I'm doing it wrong.

New to braintree. Any help would be appreciated.

Thanks

Sorry for any bad grammar

**Comment by crookedneighbor** [comment]
@d30jeff Sorry that it has taken us so long to respond to you. Can you provide a little more information about your use case?

**Comment by crookedneighbor** [comment]
Gonna close this now, but if you'd like to explain your use case more fully, we can re-open it.

**Comment by iamryanmoreno** [comment]
Hi

> Gonna close this now, but if you'd like to explain your use case more fully, we can re-open it.

I'd like to reopen this because I am encountering the same issue.
Currently the PaymentMethod accepts duplicate payment method which no way on earth we can on our Back-end side if the payment method exist or not. The only parameter on `.find` is token. Can you explain why the payment method accepts duplicates? By right this should not be happening.

**Comment by Kvm99** [comment]
yes, please fix it
