### ISSUE TITLE
Visa Checkout and Masterpass payment instrument type

### ISSUE THREAD

**Issue by yijielee** [braintree/braintree_node#113]
### General information

* SDK/Library version: 2.3.0
* Environment: Sandbox
* Language, language version, and OS: Node v6.9.4

### Issue description

I was wondering if [payment_instrument_types.js](https://github.com/braintree/braintree_node/blob/master/lib/braintree/payment_instrument_types.js) is meant to include Visa Checkout and Masterpass?

**Comment by crookedneighbor** [comment]
It definitely should. Would you like to open a PR?

The keys are:

```
VisaCheckoutCard: 'visa_checkout_card',
MasterpassCard: 'masterpass_card'
```

**Comment by yijielee** [comment]
Closing with https://github.com/braintree/braintree_node/pull/115
