### ISSUE TITLE
[WebhooksNotification] TypeError: Cannot read property 'match' of undefined

### ISSUE THREAD

**Issue by nalexeric** [braintree/braintree_node#119]
### General information

* SDK/Library version: 2.3.0
* Environment: Production
* Language, language version, and OS: Meteor 1.6 - Node 8.9.0 running inside a docker container (based on Debian). Also had the same issue on earlier Meteor versions which are based on node 4.6

### Issue description

I have a webhook set up in order to update some records in the database whenever a subscription is charged successfully. For this sole purpose, I'm using a small express app which has only one `POST` route that handles the notifications. 

From time to time, I'm getting the error in the title: `TypeError: Cannot read property 'match' of undefined`. Please note that this is not happening for all subscriptions (i.e. webhooks calls), but only for some. The only "special" thing that I'm doing in the webhook logic is that I'm wrapping the callback function with a Meteor specific method, `bindEnvironment` [(see details here)](https://guide.meteor.com/using-npm-packages.html#bind-environment), which is a very common pattern in Meteor, and has worked perfectly for almost a year until a few months ago.

**Relevant code snippet:**
```
const app = express();

app.post('/braintree', function (req, res) {
    gateway.webhookNotification.parse(
        req.body.bt_signature,
        req.body.bt_payload,
        Meteor.bindEnvironment(function (err, notification) {
            console.log(`[Webhook Received ${notification.timestamp}] | Kind: ${notification.kind}`);
            if (err) {
                // handle error
            } else {
                // handle parsed notification
            }
        })
    );
    res.status(200).send();
});
```

**Full error:**
```
11/16/2017 7:20:20 PMTypeError: Cannot read property 'match' of undefined
11/16/2017 7:20:20 PM    at WebhookNotificationGateway.parse (/opt/meteor/dist/bundle/programs/server/npm/node_modules/braintree/lib/braintree/webhook_notification_gateway.js:20:17)
11/16/2017 7:20:20 PM    at WebhookNotificationGateway.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/braintree/node_modules/@braintree/wrap-promise/wrap-promise.js:17:33)
11/16/2017 7:20:20 PM    at imports/api/payments/webhooks.js:11:33
11/16/2017 7:20:20 PM    at Layer.handle [as handle_request] (/opt/meteor/dist/bundle/programs/server/npm/node_modules/express/lib/router/layer.js:95:5)
11/16/2017 7:20:20 PM    at next (/opt/meteor/dist/bundle/programs/server/npm/node_modules/express/lib/router/route.js:137:13)
11/16/2017 7:20:20 PM    at Route.dispatch (/opt/meteor/dist/bundle/programs/server/npm/node_modules/express/lib/router/route.js:112:3)
11/16/2017 7:20:20 PM    at Layer.handle [as handle_request] (/opt/meteor/dist/bundle/programs/server/npm/node_modules/express/lib/router/layer.js:95:5)
11/16/2017 7:20:20 PM    at /opt/meteor/dist/bundle/programs/server/npm/node_modules/express/lib/router/index.js:281:22
11/16/2017 7:20:20 PM    at Function.process_params (/opt/meteor/dist/bundle/programs/server/npm/node_modules/express/lib/router/index.js:335:12)
11/16/2017 7:20:20 PM    at next (/opt/meteor/dist/bundle/programs/server/npm/node_modules/express/lib/router/index.js:275:10)
```

**Comment by jaypatel512** [comment]
Hey @nalexeric !

Reviewing the code in [webhook_notification_gateway](https://github.com/braintree/braintree_node/blob/master/lib/braintree/webhook_notification_gateway.js#L20), it looks like this error would be thrown if `payload` is passed empty (undefined). 

Ideally, we should be throwing a proper exception if any of those two values are empty. However, I am not sure WHY you are receiving empty payload. We are still looking into that.

**Comment by nalexeric** [comment]
I'll try and set up better logging and gather some data over the weekend. 
Is there anything I could be doing wrong in the gateway settings that affects the webhook payload?

**Comment by crookedneighbor** [comment]
@nalexeric Did you derive anything from your logging?

There's nothing I can think of in your GW settings that would affect this.

**Comment by jaypatel512** [comment]
Hey @nalexeric !

We added a check in 2.7.0 release to make sure the payload and signature is not null. This should atleast help you identify the error a bit better. I am going to close this issue based on inactivity, but do let us know if this fix does not help you figure out your issue. Thanks again for the patience.

**Comment by nalexeric** [comment]
I've finally managed to make some time _over the weekend_ to tackle this issue and found what was causing it. 

I've extracted the webhook processing into a standalone node app and it seems that the reason why the notification was empty sometimes is because it was larger than `bodyparser`'s default limit of 100kb. I increased that limit to 5mb and everything is finally working as expected. 

I think it would be helpful to add all these details in the documentation. It's an issue that can be easily overlocked since it's not happening for all the transactions and you can be fooled into thinking that all the recurring transactions are processed correctly if you're not checking thoroughly. In our case, it was a customer who first made us aware of the issue after not receiving his invoice one month.
