### ISSUE TITLE
Unexpected Error when deploying braintree server on firebase functions

### ISSUE THREAD

**Issue by ATF19** [braintree/braintree_node#120]
### General information

* SDK/Library version: 2.4.0
* Environment: Sandbox
* Language, language version, and OS: Node v46.11.1 on firebase functions

### Issue description

On firebase, the app just return an unexpectedError on the error object without specifying an understandable error message.
But the weird part is that it works well on my local server (using firebase serve locally).

Here's how i generate a token:
```
gateway.clientToken.generate({}, function (err, response) {
    if(response)
      res.send({error: false, token: response.clientToken});
    else
      res.send({error: true, errorObj: err, response: response});
  });
```

**Comment by crookedneighbor** [comment]
@ATF19 Can you post here what the solution was in case this comes up in the future?

**Comment by ATF19** [comment]
The problem wasn't with Braintree SDK, it was with firebase functions policy.
It's because firebase limits (and even blocks) the outgoing socket connections to non-Google controlled endpoints. 
So to solve this i had to change the cloud provider. (Or if you are facing this problem you can upgrade your firebase subscription to the blaze plan)

**Comment by crookedneighbor** [comment]
Thanks for the info. That's helpful!
