### ISSUE TITLE
Types for Braintree Node.js library

### ISSUE THREAD

**Issue by AllanSimoyi** [braintree/braintree_node#121]
Haven't been able to find any typings for Braintree. The only typings i have come across are for braintree-web, none for the server-side library.

Can someone assist regarding this?

**Comment by crookedneighbor** [comment]
I assume you mean for Typescript or something similar. Braintree doesn't use Typescript when developing this library (the braintree-web one is community created, not made by Braintree), so we don't have a type file for it.

If you'd like to provide your own type file for it, you can open a PR on https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by techieshark** [comment]
+1 for type definitions; it seems the Braintree API docs would be a pretty good place to look for anyone able to start with that. 

Perhaps a path forward would be similar to [that taken by Stripe](https://github.com/stripe/stripe-node/issues/296#issuecomment-432724760), where the community has created the type definitions and this repo would just contain documentation on how to use them.

**Comment by koldoon** [comment]
+1 for type definitions. Many serious financial projects use static type checking and typescript in common to minimise amount of errors in production.

**Comment by smrubin** [comment]
For reference, a definition was published on DefinitelyTyped: https://www.npmjs.com/package/@types/braintree

**Comment by techieshark** [comment]
@smrubin legend, thanks!
