### ISSUE TITLE
 braintree.transaction.sale,  braintree.clientToken.generate response Arrays

### ISSUE THREAD

**Issue by choychris** [braintree/braintree_node#122]
### General information

* SDK/Library version: 2.4.0
* Environment: Sandbox
* Language, language version, and OS: Node 6.11.1 , MacOS 10.12.6, Express 4.14.0, running in Docker image Node 6.11.1

Description:
Expected:
Response from braintree.transaction.sale: properties inside should be a string or object. 
, and response from braintree.clientToken.generate: clientToken should be a string

Actual result:
Response from braintree.transaction.sale and braintree.clientToken.generate are in Array.
(please check the screenshots)

Possible related issue:
[https://github.com/Leonidas-from-XIV/node-xml2js/issues/325 ](https://github.com/Leonidas-from-XIV/node-xml2js/issues/325 )

![incorrect response 1](https://user-images.githubusercontent.com/20982609/34450985-4f5a7c0e-ed54-11e7-819d-081312f58245.png)
![incorrect response 2](https://user-images.githubusercontent.com/20982609/34450986-4f810ca2-ed54-11e7-8299-b924e83ef9fc.png)
<img width="345" alt="screen shot 2017-12-23 at 12 49 59 pm" src="https://user-images.githubusercontent.com/20982609/34450987-4fa6be16-ed54-11e7-92e7-b002b1bd7e93.png">

**Comment by crookedneighbor** [comment]
I'm using the exact node version you provided and I can't reproduce this. 

If you remove the node_modules folder and re-install, do you see the same behavior?

What version of npm are you using?

The behavior in the issue you linked to should only occur in v0.2.x and higher of xml2js and we use v0.1.13. Wondering if your version of npm is buggy and not using the correct version of xml2js. Can you check the version it's using?

**Comment by choychris** [comment]
We are using Docker image Node 6.11.1 to standardise our development environment. We have tried rebuilding the image and check in Docker that "xml2js" is in  "0.1.13".
This issue only occurs in several computers, and we are out of ideas.

**Comment by choychris** [comment]
We are getting this issue too: 
https://github.com/braintree/braintree_node/issues/18
Are they some how correlated ?

**Comment by crookedneighbor** [comment]
Possibly, that's why I'm curious about what version of `npm` you are using. I will attempt to reproduce with the Node 6.11.1 docker image later today.

**Comment by crookedneighbor** [comment]
Can't find v6.11.1 in https://hub.docker.com/_/node/

I used

```
docker pull node:6.12.2
```

and could not reproduce the issue.

Where are you pulling the node container from?

**Comment by crookedneighbor** [comment]
Also, happy to look at a repo if you can create one that reproduces the issue (leaving off your API keys, of course)

**Comment by crookedneighbor** [comment]
@choychris Any updates? I'd love to fix this, but need to figure out the cause first. 😥

**Comment by choychris** [comment]
@crookedneighbor 
Thanks.
We are using npm v3.10.10
Basically, we are developing based on the same repo within Docker. But the issue only exists in some computers. So, we do not have a exact repo that will reproduce the issue.

The below is our docker setup.
![docker compose yml](https://user-images.githubusercontent.com/20982609/34594046-ae11ca90-f209-11e7-887f-99fd8a15efb6.png)
![docker-compose](https://user-images.githubusercontent.com/20982609/34594047-ae400ea0-f209-11e7-8987-b644b478124f.png)

What we are trying to do now is rebuilding Docker image to Node 6.11.5 and npm cache clean.
Will update you soon.

**Comment by choychris** [comment]
@crookedneighbor 
Turns out, even in Docker we need to npm cache clean before we install braintree module.
Maybe another version of xm2js is cached.
This could be same as the npm cache problem in issue #18 .

Anyway, thanks for the help.
Chris

**Comment by crookedneighbor** [comment]
Makes sense. Glad you were able to figure it out.
