### ISSUE TITLE
Search subscriptions by customerId

### ISSUE THREAD

**Issue by mgarchagudashvili** [braintree/braintree_node#128]
Is there a way to search subscriptions by customerId? Also, if customer object would return  subscriptions object directly would be more helpful. Currently, I can get subscriptions under payment methods objects.

**Comment by sdcoffey** [comment]
Hey @mgarchagudashvili,

Thanks for the feedback, that's useful for us to hear. Currently, there is no way to search subscriptions through a customer id.

What you can do, however, is a [customer find](https://developers.braintreepayments.com/reference/request/customer/find/node), which will return you information about a customer, including [payment methods](https://developers.braintreepayments.com/reference/response/customer/node#payment_methods), which in turn contain [subscriptions](https://developers.braintreepayments.com/reference/response/credit-card/node#subscriptions) associated with that customer. 

I'm going to close this issue, but please let me know if I'm misunderstanding your request and the above recommendation doesn't fit your use case.

**Comment by ginovski** [comment]
@sdcoffey What about when customer deleted their payment method? Currently, I have an issue that I can't get transactions and subscriptions from customer.id when the payment method is deleted.

**Comment by crookedneighbor** [comment]
@ginovski reach out to our support team for help with your integration: https://help.braintreepayments.com/

**Comment by newpdv** [comment]
> @sdcoffey What about when customer deleted their payment method? Currently, I have an issue that I can't get transactions and subscriptions from customer.id when the payment method is deleted.

I can assume that if the payment method is deleted, the subscription can no longer exist

**Comment by ChuckJonas** [comment]
@newpdv

Just tested this and subscription will still exist but will be `canceled`.

It will no longer show up in the customer object (as the payment method goes away).  So there is no way to get canceled subscriptions for customers on deleted payment methods, unless you already know the ID.

**Comment by paq85** [comment]
> Just tested this and subscription will still exist but will be canceled.
> It will no longer show up in the `getCustomer` response (as the payment method goes away). So there is no way to get canceled subscriptions for customers on deleted payment methods.

This is quite a big limitation :|

**Comment by benheb** [comment]
@ginovski did you ever find a solution for this?

**Comment by gwdp** [comment]
Going through an app integration with Braintree and was looking for the same thing.

If using drop-in UI I believe this might be an issue, but if doing self implementation maybe would be a good idea to prevent a user from deleting a payment method if associated with a subscription and ask for a new payment method to be associated with that subscription before allowing to delete the payment method.

**Comment by SeriousMonk** [comment]
Subscriptions associated with deleted payment methods are canceled. However I want to consider a subscription valid if the payedThroughDate hasn't been reached yet, even if the subscription is marked as Canceled.

This would allow the user to remove a payment method (and therefore cancel the connected subscriptions), but let him keep using the perks of the subscription until the payedThroughDate.

It would be very convenient I we were able to retrieve subscriptions by customerId to achieve this.

**Comment by SeriousMonk** [comment]
For anyone reading, this can be achieved by using Subsciprion:Search https://developer.paypal.com/braintree/docs/reference/request/subscription/search
