### ISSUE TITLE
Different error for invalid payloads

### ISSUE THREAD

**Issue by kylealwyn** [braintree/braintree_node#129]
Not a bug, just a small suggestion after integrating.

I had this code after some copy-pasta while moving over from Stripe: 
```js
const results = await braintree.customer.create({
      paymentMethodNonce: nonce,
     // `metadata` instead of `customFields`
      metadata: {
        user_id: user.id,
      },
});
```

It's misleading to throw an `AuthorizationError` when sending invalid fields in a gateway call. Something along the lines of `MalformedPayload` or `BadRequest` seems like it would be more helpful. It would then mimic more closely http statuses 401 Unauthorized and 400 Bad Request or 422 UnprocessableEntity. The misnamed (or extra in my case) fields seem to have nothing to do with Authorization, which led me down the rabbit hole of thinking my keys were wrong.

I understand now it's in the documentation but still believe to be a misnomer. Thanks!

**Comment by crookedneighbor** [comment]
This is fixed (finally) in https://github.com/braintree/braintree_node/blob/master/CHANGELOG.md#2110
