### ISSUE TITLE
merchantAccountId not supported by lineItems in transaction gateway

### ISSUE THREAD

**Issue by blugavere** [braintree/braintree_node#133]
SDK: 2.8
Environment: Sandbox 
{ invalidKeysError: These keys are invalid: lineItems[merchantAccountId]

Node 8.9.4

Looks like this is being implemented in the latest releases. 
https://developers.braintreepayments.com/reference/request/transaction/sale/node#line_items

Is merchantAccountId not supported yet?

### General information

* SDK/Library version: 
* Environment: 
* Language, language version, and OS:

**Comment by quinnjn** [comment]
Hi @blugavere 

Can you provide a snippet of your transaction sale request?

**Comment by quinnjn** [comment]
I'm making an assumption that you have something like this:
```
{
  lineItems: {
    merchantAccountId: "..."
  }
}
```

If this is the case, I don't think you'd want to put a `merchantAccountId` as a line item property.

Did you mean to include a `merchantAccountId` as a top level param? See this [example on using Merchant Account IDs for gateway.transaction.sale](https://developers.braintreepayments.com/reference/request/transaction/sale/node#specify-merchant-account).

**Comment by blugavere** [comment]
ah yep, misread the docs, thanks!
