### ISSUE TITLE
"Cannot find module 'semver'"

### ISSUE THREAD

**Issue by epilkis** [braintree/braintree_node#135]
### General information

* SDK/Library version: 2.9.0
* Environment: Sandbox
* Language, language version, and OS: Node v6.10

### Issue description

Starting out with the SDK. Running basic code in my index.js

var braintree = require("./lib/braintree.js");
var gateway = braintree.connect({
        environment: braintree.Environment.Sandbox,
        merchantId: "xxx",
        publicKey: "yyy",
        privateKey: "zzz"
    });
    
    gateway.clientToken.generate({}, function (err, response) {
        if(err){
            console.log('clientToken gen error',err);
        }else{
            console.log("clientToken response",response.clientToken);
        }
    });

The Error stack I am getting:

Response:
{
  "errorMessage": "Cannot find module 'semver'",
  "errorType": "Error",
  "stackTrace": [
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/lib/braintree/util.js:3:14)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)"
  ]
}

Unable to import module 'index': Error
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/lib/braintree/util.js:3:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by crookedneighbor** [comment]
Can you remove your node modules folder and reinstall everything? Seems like something went wrong in the install process.

**Comment by epilkis** [comment]
Hi,
Thank you for the reply. Had to fix my dependencies and make sure they're all in node_modules directory.

**Comment by epilkis** [comment]
Hi,
Thank you for the reply. Had to fix my dependencies and make sure they're all in node_modules directory.
