### ISSUE TITLE
Bluebird .each, async/await, and Search stream incompatibilities

### ISSUE THREAD

**Issue by CodeOtter** [braintree/braintree_node#136]
I'm trying to run multiple transaction searches, but the SDK specifically has `search` returning a stream.  This makes integration with `async/await` functionality and Bluebird `.each` extremely difficult.

Below is the code I have and my following assumptions about it are wrong:

* The `resolve` in the returned Promise should contain the JSON data, but it doesn't.
* The `results` should be an array of JSON, but it's an array of functions instead.
* I suspected greater support for async/await and Braintree, but nothing explains how to perform multiple searches with BlueBird and async/await.
* I can settle for using the `search` response argument's `.each`, but no examples exists on how to make that work with async/await or Bluebird either.

Should I just use the legacy callback methodology of and utilize caolan's `async` library instead?  Does pipe functionality even exist in other languages?  How do the other Braintree SDKs deal with this problem?

Here's what I got so far:

```
import Promise from 'bluebird';
import moment from 'moment';
import JSONStream from 'JSONStream';

const braintreeInstance = BraintreeModule.connect({ ... });

async function getAllTransactions(start?: Number, hourRange?: Number): Promise<Object> {
    if(start === undefined) {
        // Start at the beginning of time
        start = 0;
    }
    const startMoment = moment(start);
    const startTime = startMoment.toISOString();

    if(hourRange === undefined) {
        // End in an hour
        hourRange = 1;
    }

    const endTime = startMoment.add(3, 'days').toISOString();

    // Get the results of all transaction types in parallel
    const results = await Promise.each([
        search => search.createdAt().between(startTime, endTime),
        search => search.authorizedAt().between(startTime, endTime),
        search => search.submittedForSettlementAt().between(startTime, endTime),
        search => search.settledAt().between(startTime, endTime),
    ], async (searchMethod) => {
        const jsonTransform = JSONStream.stringify(false);

        const stream = braintreeInstance.transaction.search(searchMethod)
            .pipe(jsonTransform)
            .on('error', err => {
                jsonTransform.emit('error', err);
            });

        return new Promise((resolve, reject) => {
            stream.on('end', resolve);
            stream.on('error', reject);
        });
    });

    return results;
}

getAllTransactions();
```

**Comment by jackellenberger** [comment]
Hey @CodeOtter, there aren't any great comparisons to be made to other languages' SDKs as Node is the only one to support a stream response. Our recommendation to get the async handling you're looking for is unfortunately what you suggested, to use the [iterable responses pattern](https://developers.braintreepayments.com/reference/general/searching/search-results/node#iterable-responses) and wrap the legacy callback methodology. 

We will look into replicating this and putting up an example if we can find an elegant solution. If you run into any trouble with iterable responses please reopen this issue, or contact support directly using the link on the bottom of any developer docs page.
