### ISSUE TITLE
Android Custom Keyboards Registering as Invalid Cards

### ISSUE THREAD

**Issue by mrboli** [braintree/braintree_node#137]
### General information

* SDK/Library version: 2.10.0
* Environment: All
* Language, language version, and OS: node v9.11

### Issue description

Exactly the same as this: https://github.com/braintree/braintree-web/issues/234
Basically, the hosted fields isn't reading the inputs correctly when it's an android phone with a custom keyboard (including Samsung phones with their default keyboard).

**Comment by mrboli** [comment]
@quinnjn Let me double check this, but we're using `hostedFields` without `brain-tree` web, just `braintree`!

**Comment by crookedneighbor** [comment]
Like Quinn said,  [braintree-web](https://github.com/braintree/braintree-web) is the repo for the client side JavaScript SDK. Whether you're using npm or the hosted script from Braintree, braintree-web is the repo where the source code for those files is. Please update to the latest version of the JS library (3.32.1) and if the issue persists, leave a comment on the issue you linked to https://github.com/braintree/braintree-web/issues/234
