### ISSUE TITLE
Getting an AuthenticationError when using `serviceFeeAmount` in `transaction.sale` (Braintree Auth)

### ISSUE THREAD

**Issue by clarete** [braintree/braintree_node#139]
### General information

* SDK/Library version: 2.9.0
* Environment: sandbox
* Language, language version, and OS: node 8.4.0

### Some context

I'm trying to integrate Braintree Auth (Thanks for the cool product!) to the product I'm working on (https://opencollective.com) and our use case can be summarized as a platform that provides fiscal sponsorship for collectives that want to receive donations. We have 4 different user types here:

1) The `Collective` that wants to receive donations
2) The `Backer` that donates money to the `Collective`
3) The `Host` that will receive and store the donations on behalf of the `Collective`
4) Our `Platform` that connects every one above

### What I've accomplished so far:

(since Open Collective is libre software, I linked the bits of the implementation where it makes sense, so you can see how I'm using the `braintree` node package. [And here's the full implementation](https://github.com/opencollective/opencollective-api/blob/1699add83c878c05759a8fe987ba2b345665d0ea/server/paymentProviders/paypalbt/index.js)).

#### OAuth flow for the Host
 * Created a Braintree Sandbox account and linked it up to the PayPal Sandbox account;
 * Created an OAuth application in the Braintree Control Panel
 * Created an OAuth gateway with the keys of the application generated above
 * [Created an endpoint in the `Platform` so the `Host` can connect their Braintree/PayPal account via the OAuth flow (I'm using `gateway.oauth.connectUrl` for that)](https://github.com/opencollective/opencollective-api/blob/1699add83c878c05759a8fe987ba2b345665d0ea/server/paymentProviders/paypalbt/index.js#L27)
 * [Generated a token from the code received in the OAuth callback (Using `gateway.oauth.createTokenFromCode`). Then store access token, refresh token, and other metadata associated with the `Host` account.](https://github.com/opencollective/opencollective-api/blob/1699add83c878c05759a8fe987ba2b345665d0ea/server/paymentProviders/paypalbt/index.js#L66)

#### Add PayPal button to the UI
 * [Add an endpoint to generate client tokens on the server side (Using `merchantGateway.clientToken.generate()`). The `merchantGateway` is the result of calling `braintree.connect()` with the access token generated in the OAuth flow;](https://github.com/opencollective/opencollective-api/blob/1699add83c878c05759a8fe987ba2b345665d0ea/server/paymentProviders/paypalbt/index.js#L94-L106)
 * Add the PayPal button with the client token received from the step above;
 * Add an endpoint to process the nonce received by the PayPal button;
 * [Create a customer in the vault and store the payment method nonce received from the interaction with the button. (Using `merchantGateway.customer.create({ paymentMethodNonce })`);](https://github.com/opencollective/opencollective-api/blob/1699add83c878c05759a8fe987ba2b345665d0ea/server/paymentProviders/paypalbt/index.js#L94-L106)
 * [And finally call `merchantGateway.transaction.sale()` and here's where I actually have the problem!! I'll elaborate a lil more in the next section.](https://github.com/opencollective/opencollective-api/blob/1699add83c878c05759a8fe987ba2b345665d0ea/server/paymentProviders/paypalbt/index.js#L158-L175)

### Issue description

My struggle here is to understand how the `Platform` can charge a fee from each donation we're processing on behalf of the `Host`. I did find the parameter `serviceFeeAmount` but when I pass it to `transaction.sale` I get an `AuthenticationError` that doesn't really describe what's wrong with the request.

I'm almost sure this is happening because of something I did wrong but I couldn't really figure out what's up with the `AuthenticationError` exception that I receive (the error instance doesn't have the properties `code`, `attribute` or `message`)

**Comment by crookedneighbor** [comment]
Can you post your full `transaction.sale` call here? Wondering if you're missing a required parameter (like `amount`).

**Comment by clarete** [comment]
Hi @crookedneighbor! Thank you for the response. Here's the code I'm using to perform the transactions:

```javascript
async function createTransactions(order) {
  const merchantAccount = await getMerchantAccount(order.collective);
  const merchantGateway = await getMerchantGateway(merchantAccount);
  const paymentMethodToken = await getOrCreateUserToken(merchantGateway, order);

  const amount = order.totalAmount / 100; // PayPal uses doubles to store currency
  const serviceFeeAmount = libpayments.calcFee(amount, constants.OC_FEE_PERCENT);

  const result = await merchantGateway.transaction.sale({
    merchantAccountId: merchantAccount.clientId,
    paymentMethodToken,
    serviceFeeAmount,
    amount,
    options: {
      submitForSettlement: true
    }
  });
}
```

But as I mentioned before, the transaction actually goes through if I don't use the `serviceFeeAmount` field. :(

**Comment by crookedneighbor** [comment]
Looking at the docs for `serviceFeeAmount`, it appears that its only available for [Marketplace merchants](https://developers.braintreepayments.com/guides/braintree-marketplace/overview), not BT Auth merchants https://developers.braintreepayments.com/reference/request/transaction/sale/node#service_fee_amount

I checked with our auth team and the current system is to keep track of the transactions and invoice your merchants. 

I also learned the following:

> Our Braintree Auth product is in a closed beta program at the moment, and we're in the midst of transitioning the product offering a bit. In the interim, we're not able to add new entrants to the beta.

Would you like to be placed on a list of merchants to be considered for the new offering? If so, email auth@getbraintree.com

**Comment by clarete** [comment]
Gotcha! I'll check what I can use here! Thank you for the thorough answer @crookedneighbor! And kudos for the nice and clean API. I didn't code too much to put the prototype together! Happy to find out about the business details sooner and try another solution! <o/ Have a nice day sir!
