### ISSUE TITLE
Updating customer with wrongly formatted credit card returns AuthorizationError

### ISSUE THREAD

**Issue by nherment** [braintree/braintree_node#14]
Hi.

I'm sending this customer info:
`{
    "id":"myCustomerId",
        "creditCard": {
            "cvv":"111",
            "number":"4009348888881881",
            "credit_card_exp":"11/2013",
            "cardholder":"Indiana Jones",
            "options":{
                "makeDefault":true,
                "verifyCard":true,
                "updateExistingToken":"9774s"
            }
    }
}`

Per documentation, some attributes are misformatted:
- `credit_card_exp` should be `expirationDate`
- `cardholder` should be `cardholderName`

However, the BrainTree API then returns the following error:
    `{ message: 'Authorization Error', type: 'authorizationError' }`

I'd expect the braintree API to return some specific error like 'unsupported attribute' but not an 'authorizationError' since the documentation on authorizationError is very misleading in this case:

> You’ll receive an authorization exception if the API key that you’re using is not 
> authorized to perform the attempted action according to the roles assigned to the user 
> who owns the API key.

**Comment by SrSandeepKumar** [comment]
+1 
I am going through the same kind of issue, is their any resource/solution for this.
http://stackoverflow.com/questions/29064955/braintree-nodejs-gives-an-authentication-error
