### ISSUE TITLE
not throwing  notFoundError

### ISSUE THREAD

**Issue by devvtms** [braintree/braintree_node#141]
### General information

* SDK/Library version: 2.11.0
* Environment: Sandbox
* Language, language version, and OS: node v8.10.0, macOS highSierra 10.13.5

### Issue description

Hy, i try generate client token for NON existing user, but instead of throwing notFoundError-(docs says... https://developers.braintreepayments.com/start/hello-server/node#generate-a-client-token) i receive error object.

```js
const gateway = braintree.connect({
  environment,
  merchantId,
  publicKey,
  privateKey
});
    
customerId='non_exist' 
response = await gateway.clientToken.generate({ customerId });
console.log(response)
/*
{ errors:
       { validationErrors: {},
         errorCollections: { clientToken: [Object] } },
      params: '',
      message: 'Customer specified by customer_id does not exist',
      success: false }
*/
```

**Comment by Epreuve** [comment]
Thanks for the report!  We've let our docs team know that this section needs to be updated to reflect the correct behavior of returning a validation error.
