### ISSUE TITLE
Cannot call function removeEventListener of undefined

### ISSUE THREAD

**Issue by kbariotis** [braintree/braintree_node#147]
### General information

* SDK/Library version: latest
* Environment: both
* Language: Latest Node on MacOS

### Issue description
When the OS's socket returns an error, the [`requestSocket`](https://github.com/braintree/braintree_node/blob/master/lib/braintree/http.js#L157) (which is initialised a few lines above but never entered the `socket` event) variable is not defined and throws an error when try to access it.

Tested it with [nock](https://github.com/nock/nock) and when I disabled all network requests, the above error came up.

**Comment by crookedneighbor** [comment]
Seems reasonable to check for the `requestSocket`s existence before removing the listener. We'll make this change. 

Thanks for the report!

**Comment by crookedneighbor** [comment]
This is fixed in 2.13.0
