### ISSUE TITLE
Error http unable to resolve moudle

### ISSUE THREAD

**Issue by Talkwondo** [braintree/braintree_node#148]
This is the error I get when i require the braintree
<img width="323" alt="screen shot 2018-09-08 at 14 42 04" src="https://user-images.githubusercontent.com/20122139/45254721-7cc35b00-b385-11e8-9248-e8bfdd335731.png">

does anyone know where it come from? 

thanks

**Comment by crookedneighbor** [comment]
It looks to me like you're trying to us the Braintree node server sdk with react native. Looks like the root of the problem may be this: https://github.com/facebook/react-native/issues/7686

However, I have concerns as to why you're using the server sdk within a client app. Doing so would have you leaking your production API keys to your customers.

[Here's a guide I found](https://medium.com/react-native-training/accepting-payments-in-a-react-native-app-part-3-c22828ecab13) that uses the [web sdk](https://www.npmjs.com/package/braintree-web) within a webview in react native and Amazon Web services for the server side component.
