### ISSUE TITLE
"Expiration date is required" error when creating payment method with nonce.

### ISSUE THREAD

**Issue by artchen** [braintree/braintree_node#149]
### General information

* SDK/Library version: 2.12.0
* Environment: Production
* Language, language version, and OS: Node.js v8.11.3

### Issue description

My application uses nonce to create payment method for customers. However when calling braintree api via node.js sdk 2.12.0, we got "Expiration date is required" error. Per documentation the expiration date is not required https://developers.braintreepayments.com/reference/request/payment-method/create/node.

**Comment by artchen** [comment]
```
ErrorResponse {
     errors: 
      ValidationErrorsCollection {
        validationErrors: {},
        errorCollections: [Object],
        imageUrl: 'https://assets.braintreegateway.com/payment_method_logo/unknown.png' },
     params: { paymentMethod: [Object], merchantId: 'jnm4kgtj2f3gk9jr' },
     message: 'Expiration date is required.',
     success: false,
     paymentMethod: 
      UnknownPaymentMethod {
        validationErrors: {},
        errorCollections: [Object],
        imageUrl: 'https://assets.braintreegateway.com/payment_method_logo/unknown.png' } }
```

**Comment by artchen** [comment]
We call braintree api with: 
```
gateway.paymentMethod.create({
      customerId,
      paymentMethodNonce,
      options: {
        verifyCard: true
      }
    }, callbackFunction)
```

**Comment by artchen** [comment]
I thought only customerId and the nonce are mandatory fields to call the paymentMethod creation api. expirationDate is optional because it wasn't marked as required.

Our application launched last year and has been working fine, only today we suddenly find out all payment method creations are broken.

The error response from braintree was pasted above.

**Comment by artchen** [comment]
The iOS front-end braintree SDK we are using is of version 4.10.0 (2017-12-08).

**Comment by crookedneighbor** [comment]
What you are saying is correct, but to create a payment method, you need the tokenized nonce to represent a card details which include the expiration date.

You don't need to pass in the expiration date directly (which would require a higher level of PCI compliance), but the tokenized nonce should represent card details which include it.

Strange that it seems like the behavior has changed, I'll bring it up with the team that maintains that part and get back to you.

**Comment by xuaninbox** [comment]
we have narrow this down to iOS only, the iOS is tokenizing with the EXP dates but seems it doesn't include it in the nonce.  

See: https://github.com/braintree/braintree_ios/issues/421

**Comment by artchen** [comment]
The issue was resolved on iOS end.
