### ISSUE TITLE
Testing payment nonce

### ISSUE THREAD

**Issue by bashleigh** [braintree/braintree_node#150]
### General information

* SDK/Library version: 2.12.0
* Environment: Sandbox
* Language, language version, and OS: node 8-10, OS various (locally mac)

### Issue description

This is more of a question than an issue. Is there a testing payment nonce I can use? I was hoping I can test my system in travis using jest without having to get a payment_nonce from the client.

**Comment by crookedneighbor** [comment]
Here is the documentation around [testing nonces](https://developers.braintreepayments.com/reference/general/testing/node#payment-method-nonces)

This repo is for bugs with the sdk. For questions about your integration, the best thing to do will be to [contact our support team](https://articles.braintreepayments.com/forms/contact). They are better equipped to answer specific question about integrating with Braintree.

**Comment by bashleigh** [comment]
Thanks! I knew I'd read about it somewhere several years ago but couldn't find it!
