### ISSUE TITLE
Error: Missing publicKey

### ISSUE THREAD

**Issue by ProductOfAmerica** [braintree/braintree_node#151]
### General information

* SDK/Library version: 2.13.1
* Environment: Sandbox
* Language, language version, and OS: Node v10.13.0 on Ubuntu 16.04

### Issue description
I'm getting the following error when trying to start my server:
```
Error: Missing publicKey
    at new Config (/myserver/node_modules/braintree/lib/braintree/config.js:31:36)
    at Object.connect (/myserver/node_modules/braintree/lib/braintree.js:38:46)
    at file:///myserver/routes/utils/braintreeUtils.mjs:3:34
    at ModuleJob.run (internal/modules/esm/module_job.js:96:12)
```

Here's my code under `/routes/utils/braintreeUtils.mjs`:
```javascript
import braintree from "braintree";

export const gateway = braintree.connect({
  environment: braintree.Environment.Sandbox,
  merchantId: process.env.BRAINTREE_ID,
  publicKey: process.env.BRAINTREE_PUB,
  privateKey: process.env.BRAINTREE_PRIV
});
```

I have all my environment variables set, so I'm not sure why I'm getting this error. Anything helps, thanks!

**Comment by crookedneighbor** [comment]
Please contact our support team: https://help.braintreepayments.com/

They'll be better equipped to walk through issues with your integration. It's unlikely that this is an issue with the SDK itself.
