### ISSUE TITLE
How can I test braintreeGateway.subscription.create 

### ISSUE THREAD

**Issue by bashleigh** [braintree/braintree_node#152]
### General information

* SDK/Library version: ^2.12.0
* Environment: Sandbox
* Language, language version, and OS: TypeScript/nodejs, TS 3.0.3/nodejs 7-10.5, OSX/linux/Moby

### Issue description

So I've been building a reusable braintree module for NestJS using TypeScript in my spare time. I used the Laravel Cashier package quite some time ago now and wanted to replicate the functionality for nestjs. 
Mainly this issue is related to testing as I'm a little unsure whether I should stick to calling braintree's API or whether I should mock the responses myself by mocking BraintreeGateway. I have done so for `BraintreeGatway.transaction.sale` and it work! However I've been unable to test `BraintreeGatway.transaction.find` as I require a transaction with a state of accepted? (this issue is probably related to using a different nonce and I haven't tried any other nonces just yet, I can probably solve this one!). 

The main functionality I wanted to cover was subscriptions hence why I implemented the webhooks first. However I wanted to supply this package so it was capable of creating and managing subscriptions also! I've added some methods to manage the subscriptions but I'm struggling to test them? I need a [paymentMethodToken](https://github.com/nestjs-community/nestjs-braintree/blob/master/src/__tests__/braintree.subscription.spec.ts#L33) and I'm not quite sure how I can create a testing token? I believe PaymentMethodToken would be from the braintree client package? 
The alternative is to mock the response but I don't feel this is correct as I've also been adding typings for braintree_node and that would mean these types are not being tested! 

Also, seeing as I've been adding types for braintree_node I feel like these shouldn't be exclusive to the nestjs-braintree package I've been building and should therefore be moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) however I'm not quite so confident to do so? I've created an [issue](https://github.com/nestjs-community/nestjs-braintree/issues/19) for this and was wondering if anyone would be able to double check the types when I add them to DefinitelyTyped?

Thanks in advance! Sorry for a long winded explanation! 

Ashleigh

**Comment by crookedneighbor** [comment]
> Mainly this issue is related to testing as I'm a little unsure whether I should stick to calling braintree's API or whether I should mock the responses myself by mocking BraintreeGateway. I have done so for BraintreeGatway.transaction.sale and it work! However I've been unable to test BraintreeGatway.transaction.find as I require a transaction with a state of accepted? (this issue is probably related to using a different nonce and I haven't tried any other nonces just yet, I can probably solve this one!).

When you say it works for `transaction.sale`, I assume you mean that you are hitting the sandbox API. [`transaction.find`](https://developers.braintreepayments.com/reference/request/transaction/find/node) requires an id of transaction. I don't think it matters what the state of the transaction is. I'd contact our [support team](https://help.braintreepayments.com/) so we can better troubleshoot your integration.

>I need a paymentMethodToken and I'm not quite sure how I can create a testing token? I believe PaymentMethodToken would be from the braintree client package?

If you have the id from an existing customer, you can always add a payment method to that customer with [`paymentMethod.create`](https://developers.braintreepayments.com/reference/request/payment-method/create/node), using one of the fake nonces: https://developers.braintreepayments.com/guides/recurring-billing/testing-go-live/ruby#nonce-fake-valid-nonce

There's a additional info on that page about testing recurring billing.

> I've created an issue for this and was wondering if anyone would be able to double check the types when I add them to DefinitelyTyped?

We don't use TypeScript to develop the Braintree node sdk, so we can't help with that.

In the future, it'd be better to open a separate Github issue for each problem you are encountering, that way we can more easily address each one and close them as they get resolved. If you find a bug, please log it here, but if your question is not about a bug with the SDK, the best course is to reach out to our support team. https://help.braintreepayments.com/
