### ISSUE TITLE
Testing gateway.subscription.create fails with Authorization Error

### ISSUE THREAD

**Issue by Lwdthe1** [braintree/braintree_node#154]
### General information

* SDK/Library version: 2.15.0
* Environment: Sandbox
* Language, language version, and OS: Node v8.11.2 on macOS Mojave

### Issue description

I am trying to test my custom integration of purchasing a subscription. Everything works until I try to run `gateway.subscription.create({})`, which fails with an authorization error. I use the `braintree.Test.Nonces.Transactable` nonce and `fake-valid-no-billing-address-nonce`; both succeed to create a payment method and give me a paymentMethodToken.

It'd be nice if the authorization error said more about why the error occurred, but all I get is this:
![screen shot 2019-01-25 at 10 21 46 am](https://user-images.githubusercontent.com/5778798/51765162-e8376c00-208b-11e9-94b0-3346785f8120.png)

My code:

```
        completeSubscriptionTransactionForPayment({ dbPayment, paymentMethodToken, planId }) {
		const subscriptionSale = {
			planId,
			paymentMethodToken: paymentMethodToken,
			// Custom fields must be fields configured in control panel as follows:
			// https://articles.braintreepayments.com/control-panel/custom-fields#creating-a-custom-field
			customFields: { payment_id: `${dbPayment._id}` },
		}

		console.log('Sale data:')
		console.log(subscriptionSale)
		return Q(gateway.subscription.create(subscriptionSale))
			.then((result) => {
				console.log(result)
				return result
			})
			.fail((err) => {
				console.error(err)
				console.error(err.stack)
				throw err
			})
	}
```

Thanks in advance for your help.

**Comment by Lwdthe1** [comment]
Hmmm.... I just removed the customFields and it worked. But I have the custom field that I want to pass in configured in my sandbox:
<img width="979" alt="screen shot 2019-01-25 at 10 32 26 am" src="https://user-images.githubusercontent.com/5778798/51765444-9b07ca00-208c-11e9-844a-da43c6f0cf22.png">

Are custom fields not allowed for subscriptions?

**Comment by crookedneighbor** [comment]
Custom fields are not supported for subscriptions. 

You can create a subscription object in your own database that correlates with the Braintree one and include any custom fields you need.

Also, no need to use `Q`. `gateway.subscription.create` will return a promise if no callback is provided.

**Comment by Lwdthe1** [comment]
Thanks for clarifying.

As for the `Q()` wrapping, I need to do that because I use Q as my promise library, which uses  `.fail()`, whereas the gateway uses `.catch()`. Mongoose allows for me to set my preferred promise library, but I have not found a way to do that with Briantree. Is that possible?

**Comment by crookedneighbor** [comment]
No, there's no global configuration for what promise library to use. According to the [Q documentation](https://github.com/kriskowal/q), you can use `catch` if using a version of node that supports promises.
