### ISSUE TITLE
Question: Client token exposed

### ISSUE THREAD

**Issue by prasadh13** [braintree/braintree_node#157]
### General information

* Environment: Sandbox
* Language, language version, and OS: Node

### Issue description

I have been testing my application for vulnerabilities and was wondering if exposing the client token generated will be a security threat. It is right now encoded which can be decoded by an online tool and I can see all configurations of my sandbox account. Will that be of any concern in the future?

**Comment by crookedneighbor** [comment]
That is not a concern. All the data encoded in it is okay for public consumption. Even more data is exposed when the configuration is fetched on the client side.

**Comment by prasadh13** [comment]
Thank you for the promptness.
