### ISSUE TITLE
Unknown or expired payment_method_nonce

### ISSUE THREAD

**Issue by disappearer** [braintree/braintree_node#159]
### General information

* SDK/Library version: 2.18.0
* Environment: Sandbox
* Language, language version, and OS: Node 12.6.0, OSX

### Issue description

Hello and sorry if this is the wrong place to ask, but I don't have a better idea. I'm getting the following message upon attempting to make a test transaction `Unknown or expired payment_method_nonce.`. My backend code:
```javascript
const express = require('express');
const bodyParser = require('body-parser');

const app = express();
const port = 3000;

const braintree = require('braintree');

const gateway = braintree.connect({
  environment: braintree.Environment.Sandbox,
  merchantId: '****',
  publicKey: '****',
  privateKey: '****'
});

app.set('view engine', 'ejs');
app.use(express.static('public'));
app.use(bodyParser.json());

app.get('/dropin', (req, res) => {
  gateway.clientToken.generate({}, (err, response) => {
    const { clientToken } = response;
    res.render('pages/dropin', { clientToken });
  });
});

app.post('/checkout', function(req, res) {
  const nonceFromTheClient = req.body.nonce;
  console.log('nonceFromTheClient: ', nonceFromTheClient);
  gateway.transaction.sale(
    {
      amount: '10.00',
      paymentMethodNonce: nonceFromTheClient,
      options: {
        submitForSettlement: true
      }
    },
    function(err, result) {
      console.log('result: ', result);
      console.log('err: ', err);
    }
  );
});

app.listen(port, () => console.log(`Example app listening on port ${port}!`));
```
Since we didn't manage to use existing components for react native we decided to go with WebView and load a dropin html `res.render('pages/dropin', { clientToken });`. This is the react native component for what it's worth:
```javascript
const PaymentPlayground: PaymentPlaygroundT = ({ navigation }) => {
  const handleMessage = (event: WebViewMessageEvent) => {
    const data = JSON.parse(event.nativeEvent.data);
    console.log('data: ', data);
    const { nonce } = data;
    
    fetch('http://localhost:3000/checkout', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ nonce }),
    });
  };
  return (
    <WebView
      source={{ uri: 'http://localhost:3000/dropin' }}
      style={{ marginTop: 20 }}
      onMessage={handleMessage}
      
    />
  );
};
```
This is the result from the `gateway.transaction.sale()` call
```
result:  ErrorResponse {
  errors: ValidationErrorsCollection {
    validationErrors: {},
    errorCollections: { transaction: [ValidationErrorsCollection] }
  },
  params: {
    transaction: {
      amount: '10.00',
      paymentMethodNonce: 'tokencc_bh_j6y779_3c3shq_k78swh_k4w4rg_wm6',
      options: [Object],
      type: 'sale'
    }
  },
  message: 'Unknown or expired payment_method_nonce.',
  success: false
}
```
The card number that I'm using is `4111111111111111`. The nonce is always different, fresh, unused and I don't seem to be using multiple merchant ids. When I use values like `fake-valid-nonce` it works fine. Does anyone know what is the problem or if this is even supposed to work all together?

**Comment by Epreuve** [comment]
It looks like your client is using a hardcoded client token from our demo/docs example.  This means the nonce created in your client side app "belongs" to our demo sandbox, and when passed to your server setup with your own sandbox API credentials, you're not authorized to use the nonce as it's not found as one belonging to your account.

You'll need to make sure you either [generate a client token](https://developers.braintreepayments.com/start/hello-server/node#generate-a-client-token) in your server and pass it to your client to be used when setting up the JS SDK, or, us a [tokenization key](https://developers.braintreepayments.com/guides/authorization/tokenization-key/javascript/v3) belonging to your account.

For more help with this, please reach out to [Braintree support](https://help.braintreepayments.com/).

**Comment by disappearer** [comment]
Hello, my client is not using a client token at all. Because my backend serves the dropin html, I fetch it before that with 
```javascript
app.get('/dropin', (req, res) => {
  gateway.clientToken.generate({}, (err, response) => {
    const { clientToken } = response;
    res.render('pages/dropin', { clientToken });
  });
});
```

**Comment by disappearer** [comment]
I'm very sorry, you were actually right! I was initially using my own generated client token, but had it changed in the course switching to hosted fields. Thank you and sorry for wasting your time :)
