### ISSUE TITLE
subscription.find works, subscription.update : notFoundError 

### ISSUE THREAD

**Issue by krismeister** [braintree/braintree_node#161]
### General information

* SDK/Library version: 2.19.0
* Environment:  sandbox
* Language, language version, and OS: Node v10.15.1 on Mac

### Issue description

When calling update subscription with an ID, the API returns a notFoundError error.
The same ID works with subscription.find()

```javascript
function updateWithNonce(subscription, nonce) {
  console.log('we are trying to update this subscription', subscription.id);
  console.log('we are trying to update to this nonce', nonce);
  return new Promise( (resolve, reject)=> {

    braintreeGateway.subscription.find(subscription.id, function (err, result) {
      console.log('find did work, here is the plan id, ', result.planId);
    });

    braintreeGateway.subscription.update(subscription.id, {
      paymentMethodToken: nonce,
      planId: "month_to_month_2995"
    }, function (err, result) {
      console.log('updated a payment result', result);
      console.log('updated a payment err', err);
      if(err) {
        reject(err)
      } else {
        resolve(result);
      }
    })
  })
}
```

The output is as follows. You can see the find works fine.

```
we are trying to update this subscription 7wj49r
we are trying to update to this nonce b575bb1d-a5ca-0839-583d-001c7346a6aa


updated a payment result undefined
updated a payment err { notFoundError: Not Found
    at Object.NotFoundError (/Users/kris/fast_workspace/php/callingvault/cv7/api2/node_modules/braintree/lib/braintree/exceptions.js:7:15)
    at Http.checkHttpStatus (/Users/kris/fast_workspace/php/callingvault/cv7/api2/node_modules/braintree/lib/braintree/http.js:28:37)
    at Http.<anonymous> (/Users/kris/fast_workspace/php/callingvault/cv7/api2/node_modules/@braintree/wrap-promise/wrap-promise.js:18:33)
    at IncomingMessage.response.on (/Users/kris/fast_workspace/php/callingvault/cv7/api2/node_modules/braintree/lib/braintree/http.js:95:28)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) name: 'notFoundError', type: 'notFoundError' }


find did work, here is the plan id,  month_to_month_2995

```

**Comment by Epreuve** [comment]
@krismeister Assuming you're generating the nonce with the Drop-in, you will want to change `paymentMethodToken` to `paymentMethodNonce` in your `braintreeGateway.subscription.update` call.  

The relation can be confusing in this context, but they are two different values entirely, and since the nonce value represents a token, but the nonce string itself _isn't_ a token, that's why you'd get a 404.  You can take a look [here in the docs](https://developers.braintreepayments.com/reference/request/subscription/update/node#payment_method_nonce) for more details about the two parameters and their specifics.

**Comment by krismeister** [comment]
Wow, thanks for the quick reply.

You're right i'm using the drop-in UI.
Ok its when I swapped to "paymentMethodNonce" it start working.

Thanks again!
