### ISSUE TITLE
gateway.transaction.search stream nor callback is resulting in data

### ISSUE THREAD

**Issue by KenEucker** [braintree/braintree_node#165]
### General information

* SDK/Library version: 2.22.0
* Environment: Production
* Language, language version, and OS: Node v13.9.0 on Ubuntu 19.10

### Issue description
What I am trying to accomplish: to retrieve the 5 most recent transactions, or all of the transactions, for a given customer.

I am having issues with the `gateway.transaction.search` method and how it handles results. I wish this method was promise based like others as I'm having a tough time working with the stream and then ultimately with calling .each on the result. This is the documentation that I am following: https://developers.braintreepayments.com/reference/request/transaction/search/node

Code illustration of using the callback:
```
return new Promise((resolve) => {
        const transactions = []
        const stream = braintreeGateway.transaction.search(function(s) {s.customerId(customerId).is()},
            (err, response) => {
                response.each(function(err, transaction) {
                    transactions.push(transaction)
                })
                resolve(transactions)
        })
}
```

Code illustration of using the returned stream object:
```
return new Promise((resolve) => {
        const transactions = []
        const stream = braintreeGateway.transaction.search(function(s) {s.customerId(customerId).is()})

        stream.on("data", function(transaction) {
            console.log("data", {transaction})
            transactions.push(transaction)
        })

        stream.on("end", (t) => {
            console.log("end", {transactions})
            resolve(transactions)
        })

        stream.resume()
})
```
In both of these examples, I cannot get a promise to resolve with an array full of the transactions I am expecting to see for the customer IDs I try sending along. I've confirmed that the customers I am looking at do have transactions in their history.

In example 1, with the callback, the .each method doesn't appear to reach the code inside it's callback.

In example 2, with the stream, the on("data" callback is not reached either.

This would make me think that the API is not returning any results but I know that can't be. Any help steering me in the right direction would be greatly appreciated.

**Comment by crookedneighbor** [comment]
I'm not surprised that the callback example doesn't work as expected, because `each` in this case is not synchronous. The search callback should basically be a list of ids, and when you call `each` on it, it lazy loads those transactions in batches, so when you immediately `resolve` after calling each, you miss the transactions.

I am surprised that the stream version you posted doesn't work though. Please reach out to our support team so we can investigate your account more closely: https://help.braintreepayments.com/

**Comment by KenEucker** [comment]
@crookedneighbor Braintree support was contacted last week, though I have not directly been involved in those emails as this issue was linked.

In example 1, even if I put the resolve inside the .each (returning the first result) this does not work.

I'd love to see a working example from your team with verifiable results.

**Comment by crookedneighbor** [comment]
Figured out the problem. For both the examples, you're doing:

```js
braintreeGateway.transaction.search(function(s) {
  s.customerId(customerId).is()
}
```

When you want to be doing:

```js
braintreeGateway.transaction.search(function(s) {
  s.customerId().is(customerId)
}
```
