### ISSUE TITLE
"Postal code is required" on paymentMethod.update

### ISSUE THREAD

**Issue by stolinski** [braintree/braintree_node#166]
### General information

* SDK/Library version: "braintree": "^2.22.0"
* Environment: both
* Language, language version, and OS: node 12.16

### Issue description

I'm getting "Postal code is required" when running:
```
          const res = await gateway.paymentMethod.update(paymentMethodToken, {
            options: {
              makeDefault: true,
            },
          })
```

The token in question has a postal code associated with it and added itself correctly, but when attempting to make it default, this Postal Code error pops up. 

The same error shows up when doing:
```
    const res = await gateway.customer.update(customerId, {
      defaultPaymentMethodToken: paymentMethodToken,
    })
```

I'm not sure what I should be doing different here, the token clearly shows a postal code in the sandbox backend.

I should mention that I know that customer.update is the preferred way and that's initially how I attempted.

**Comment by stolinski** [comment]
When I pass the entire bill billingAddress option in, I get an 'Authorization Error' or a message about needing the entire CC to make one the default. 

How exactly are you suppose to make an existing token the default without prompting the user for the card details again? I'm following the docs exactly and it refuses to validate an already validated and vaulted card.

**Comment by stolinski** [comment]
Long story short.

```
braintree.customer.update("theCustomerId", {
  defaultPaymentMethodToken: "theToken",
}, function (err, result) {
});
```

Does not work if you have postal code and cvv verification required.

**Comment by hollabaq86** [comment]
👋 @stolinski sorry for the delay. Adding `verifyCard: false` to either the [payment method](https://developers.braintreepayments.com/reference/request/payment-method/update/node#options.verify_card) or [customer](https://developers.braintreepayments.com/reference/request/customer/update/node#credit_card.options.verify_card) update calls should resolve your issue:

```
          const res = await gateway.paymentMethod.update(paymentMethodToken, {
            options: {
              makeDefault: true,
              verifyCard: false
            },
          })
```

Do you have [AVS Rules](https://articles.braintreepayments.com/guides/fraud-tools/basic/avs-cvv-rules) turned on for your account via the Control Panel? When they are turned on for your account, they'll apply to any API calls that change the card's record which includes making them default.

All this said, our documentation can be more clear about this behavior, and I've forwarded this feedback on to the team that owns AVS rules for review.

**Comment by stolinski** [comment]
I have AVS rules in the dashboard. What is the strategy for updating with those rules? Do you require the user to re-enter their card details?

**Comment by crookedneighbor** [comment]
@stolinski if you know that the user does not need to go through a verification process again, simply passing `verifyCard: false` like @hollabaq86 said will do the trick.

If you're doing some other kind of update that would require you to do a verification, then yes, you'd need to collect the details from the customer.

**Comment by hollabaq86** [comment]
I also recommend contacting [Support](http://help.braintreepayments.com/) if you have additional questions about updating payment methods with AVS rules in place. They can walk you through how it works in more detail than we can in a GH issue 😅

**Comment by stolinski** [comment]
Passing verifyCard false returns the same issue. I can provide reproduction. Will have to put one together tomorrow.

**Comment by crookedneighbor** [comment]
@stolinski still contact our support team so we can better correlate the logs with your API requests https://help.braintreepayments.com/

**Comment by sbosell** [comment]
Out of curiosity what was the resolution for this?

**Comment by Cartman720** [comment]
> Out of curiosity what was the resolution for this?

Well, I've faced same issue and tried to use below code:

```
const res = await gateway.paymentMethod.update(paymentMethodToken, {
  options: {
    makeDefault: true,
    verifyCard: false,
  },
});
```

Works without issues.
Node SDK version: ^3.10.0
