### ISSUE TITLE
cloneTransaction has incorrect return type in @types/braintree

### ISSUE THREAD

**Issue by jamemackson** [braintree/braintree_node#169]
### General information

* SDK/Library version: 
  * @types/braintree: 2.22.0
  * braintree: 2.22.0
* Environment: any
* Language, language version, and OS: Node 12 (any version) on MacOS

### Issue description

In `@types/braintree` the defined return type for [cloneTransaction](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/braintree/index.d.ts#L221-L224) is set to `Promise<void>` when in actuality it returns something like `Promise<ValidatedResponse<Transaction>>`.

**Comment by crookedneighbor** [comment]
We don't maintain `@types/braintree`. 

In a release in the future, the Braintree Node SDK will be converted to typescript and have its own types. Until then, you may PR definitely typed to fix the `@types/braintree` package.

**Comment by jamemackson** [comment]
Thanks @crookedneighbor.  Good to know. 👍
