### ISSUE TITLE
Master merchant account ID is invalid

### ISSUE THREAD

**Issue by sajadghawami** [braintree/braintree_node#177]
Hey there,

i am trying to integrate braintree-marketplace and i keep getting `Master merchant account ID is invalid` even though i am using the exact ID as explained from this [braintree marketplace guide](https://developers.braintreepayments.com/guides/braintree-marketplace/onboarding/node).

Here is a screenshot where i overpainted the `Merchant ID` i tried:

![Bildschirmfoto 2020-10-26 um 17 04 02](https://user-images.githubusercontent.com/11796944/97197034-74b91600-17ad-11eb-9fe0-29b0311c0c7f.png)

I also tried these two, from the section below where the `Merchant Accounts` are:

![Bildschirmfoto 2020-10-26 um 17 06 11](https://user-images.githubusercontent.com/11796944/97197406-eabd7d00-17ad-11eb-8cb4-a57ab986b9eb.png)

The `Merchant Account ID` did not work, nor did the `Unique Identifier`
 
### General information

Using `"braintree": "^3.0.0"`

### Full Error

This is the full error-message:

```js
node_1      | ErrorResponse {
node_1      |   errors: ValidationErrorsCollection {
node_1      |     validationErrors: {},
node_1      |     errorCollections: { merchantAccount: [ValidationErrorsCollection] }
node_1      |   },
node_1      |   params: {
node_1      |     merchantAccount: {
node_1      |       individual: [Object],
node_1      |       business: [Object],
node_1      |       funding: [Object],
node_1      |       tosAccepted: 'true',
node_1      |       masterMerchantAccountId: 'XXXXXXX'
node_1      |     },
node_1      |     merchantId: 'XXXXXXX'
node_1      |   },
node_1      |   message: 'Master merchant account ID is invalid.',
node_1      |   success: false
node_1      | }

```

Am i missing something?

Thanks!

**Comment by crookedneighbor** [comment]
Please reach out to our support team for assistance with this.

https://help.braintreepayments.com/
