### ISSUE TITLE
Does not provide an export named 'exceptions'

### ISSUE THREAD

**Issue by jtcooper10** [braintree/braintree_node#179]
### General information

* SDK/Library version: 3.1.0
* Environment: Sandbox
* Language, language version, and OS: JavaScript, Node v12.6.0, Fedora 32

### Issue description

The [Exceptions page](https://developers.braintreepayments.com/reference/general/exceptions/node) of the Braintree docs have a list under the `braintree.exceptions` namespace for exception handling. However, it doesn't appear that the error classes defined in `lib/exceptions.js` are actually exposed through the `braintree` default export.

It does expose `braintree.errorTypes`, however this appears to just be a dictionary of strings which match up to the type names rather than the exceptions themselves (so no `instanceof X` error handling). I can use `errorTypes` for now, but either the `exceptions` list should be exposed for exception handling or, if this is intentional, the docs may need to be updated to use the `errorTypes` namespace instead.

**Comment by crookedneighbor** [comment]
You're totally right that it's missing. Would you like to open a PR? The exceptions file is here: https://github.com/braintree/braintree_node/blob/master/lib/braintree/exceptions.js

**Comment by jtcooper10** [comment]
Thanks! Pull request opened here: #180

**Comment by crookedneighbor** [comment]
This is out in 3.2.0
