### ISSUE TITLE
Issue with the rest spread operator (...) - unexpected token

### ISSUE THREAD

**Issue by tenshis** [braintree/braintree_node#181]
When I start my application I receive the following error:

```
node_modules\braintree\lib\braintree\util.js:277
W20201208-16:31:36.034(1)? (STDERR)   static zip(...arrays) {
W20201208-16:31:36.035(1)? (STDERR)              ^^^
W20201208-16:31:36.036(1)? (STDERR)
W20201208-16:31:36.037(1)? (STDERR) SyntaxError: Unexpected token ...
```

I read this might be due to missing babel dependencies, so I attempted to add the following to the project, but the problem persists:
```
babel-plugin-transform-es2015-destructuring,
babel-plugin-transform-object-rest-spread,
babel-preset-stage-0
```

**Comment by crookedneighbor** [comment]
What version of node are you using? The current version requires 10 or higher.

**Comment by tenshis** [comment]
Yes, thank you. I was using an older version of Node. Updating it fixed the issue.
