### ISSUE TITLE
How to verify if 3DS is activated and working?

### ISSUE THREAD

**Issue by tenshis** [braintree/braintree_node#182]
I'm trying to adhere to the new European law and activate 3DS in the Braintree Drop-In before the end of the year. I know that 3DS 2 support requires Drop-in version 1.20.1 or higher, and also requires Braintree version 3.52.0 or higher.

I've added the **threeDSecure: true** flag, but see no change whatsoever, neither in the UI nor in the Braintree sandbox...

**Comment by crookedneighbor** [comment]
Please reach out to our support team so they can look over your integration: https://help.braintreepayments.com/

They can help you figure out if you are integrated correctly.
