### ISSUE TITLE
SubscriptionRequest cannot use paymentMethodNonce without paymentMethodToken

### ISSUE THREAD

**Issue by 9029jonesj** [braintree/braintree_node#183]
### General information

* SDK/Library version: 3.1.0
* Environment: Sandbox
* Language, language version, and OS: Node v12.18.2

### Issue description

When updating a subscription using the dropIn wit a clientId, a paymentMethodToken should not be required; otherwise the subscription does not get updated. This is really an issue with the TypeScript definition for the **SubscriptionRequest** interface.

**Comment by crookedneighbor** [comment]
@9029jonesj we don't maintain the types library from definitely typed.

In the future, we're planning on migrating this repo to typescript proper, at which point all the type definitions will be built in and maintained by us.

Until then, I recommend you update the types definition  to suit your needs: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/braintree/index.d.ts
