### ISSUE TITLE
threeDSecure npm package

### ISSUE THREAD

**Issue by damianpm** [braintree/braintree_node#185]
### General information

* SDK/Library version: 3.70.0
* Environment: sandbox and production
* Language, language version, and OS: Node v10
### Issue description

I'm using the npm package `braintree-web`, it includes `braintree-web/client` and `braintree-web/hosted-fields`, but it doesn't include `threeDSecure`
Does `threeDSecure` has its own npm pakage?
I know I can include the script tag to fetch `https://js.braintreegateway.com/web/3.70.0/js/three-d-secure.min.js`, but I'd like to have threeDSecure in my webpack pipeline

**Comment by hollabaq86** [comment]
👋 @damianpm this is the repo for the Node server-side SDK. Your question applies to the client-side library. I'm going to close this issue and create a new one in our client-side [braintree-web](https://github.com/braintree/braintree-web) repo.

**Comment by damianpm** [comment]
> 👋 @damianpm this is the repo for the Node server-side SDK. Your question applies to the client-side library. I'm going to close this issue and create a new one in our client-side [braintree-web](https://github.com/braintree/braintree-web) repo.

Thanks @hollabaq86 !
