### ISSUE TITLE
Venmo Payments are returning a 502 Error even though the transaction is successful

### ISSUE THREAD

**Issue by gvb26** [braintree/braintree_node#187]
<img width="1345" alt="Venmo Purchase on Sandbox" src="https://user-images.githubusercontent.com/25397326/107550184-b4f6a580-6b9e-11eb-893d-e0f1c28f9654.png">
<img width="1359" alt="Venmo Purchase on Prod" src="https://user-images.githubusercontent.com/25397326/107550259-ccce2980-6b9e-11eb-8032-e342275f3bb3.png">
<img width="1750" alt="Proof of Prod Venmo Purchase" src="https://user-images.githubusercontent.com/25397326/107550317-dfe0f980-6b9e-11eb-8643-d347f88960f2.png">

### General information

* SDK/Library version: 2.22.0
* Environment: Production
* Language, language version, and OS:  Node.js 12.x on AWS Lambda

### Issue description

I currently have Braintree transactions (Sale, Refund, Vault, Void) being called to an AWS API Gateway via AWS Lambda. As of late, any venmo sale transaction on our production environment has begun to return a 502 Internal Server Error response. In spite of this response, the transactions are successful (Venmo funds are removed from the account that committed the transaction). This only occurs for Venmo payments on Production. Other payment methods such as Apple Pay and CC are successful and return a 200 OK response and Venmo in the sandbox environment also occurs successfully. The Node code is 1:1 between sandbox and prod so I am not sure what is causing this issue all of a sudden. We require the 200 response in order to receive transaction id and other information in order to support refunding, void and other features directly on our platform. Please advise.

**Comment by hollabaq86** [comment]
👋  @gvb26 please [Contact Support](https://help.braintreepayments.com/) referencing this issue. They'll coordinate with our Venmo teams to investigate.
