### ISSUE TITLE
retry on 502/503 (on 5xx maybe)

### ISSUE THREAD

**Issue by kirillgroshkov** [braintree/braintree_node#188]
### General information

* SDK/Library version: `braintree@3.2.1`
* Environment: Production
* Language, language version, and OS: Node 14.15..4

### Issue description

I've noticed these kind of errors in our Sentry:
![image](https://user-images.githubusercontent.com/4757745/108985029-dc666b80-7690-11eb-872f-73426186112a.png)

Usually, for 99% of the 3rd-party services, we use HTTP api, where we have a setup that automatically retries on errors (on certain methods; using a fantastic https://github.com/sindresorhus/got library).

But Braintree node sdk recommends/forces us to use a client library instead of an HTTP API.

So far so good, but I believe it should still implement retry mechanisms (with exponential backoff or whatever is preferred by the Braintree http API), so it doesn't fail on such errors.

We can patch braintree SDK methods, of course, but there are so many of them, so it's largely inconvenient to do in the userland code.

So, I'm requesting to have this functionality in the sdk itself, as it should be a common practice.

**Comment by kirillgroshkov** [comment]
Another example. Different errors, but http status is still 5xx:

![image](https://user-images.githubusercontent.com/4757745/108985605-86de8e80-7691-11eb-9d27-38d7ccd0b6f6.png)

**Comment by hollabaq86** [comment]
👋    @kirillgroshkov thanks for reaching out. I think you'll be better served using our [GraphQL API](https://graphql.braintreepayments.com/). This way you don't have to worry about the SDK client library at all and can use our API directly.

If you continue to encounter 5xx errors, please [contact Support](https://help.braintreepayments.com/).
