### ISSUE TITLE
Expected types of Subscription.billingPeriodStartDate and Subscription.billingPeriodEndDate

### ISSUE THREAD

**Issue by fightbulc** [braintree/braintree_node#190]
### General information

* SDK/Library version: 3.3.0
* Environment: Both
* Language, language version, and OS: 12.22.1

### Issue description

I would like to find out what should be the expected types of the aformentioned fields.
@types/braintree defines `Date`, your website docs leave that empty and the actual response is a string.

Would be great to see what we should expect here.

Looking forward to hearing back from you.

**Comment by sestevens** [comment]
The expected type for both of those fields is a string. We'll look into updating the docs so that's more clear!

**Comment by fightbulc** [comment]
Thanks for making this clear, @sestevens

**Comment by sestevens** [comment]
The docs updates will be published soon, so I'm going to close out this issue. Thanks for bringing this to our attention!
