### ISSUE TITLE
Typo in `gateway.paymentMethod.update()`

### ISSUE THREAD

**Issue by andrescamperi** [braintree/braintree_node#191]
### General information

* SDK/Library version: 3.0.0
* Environment: Production
* Language, language version, and OS: Node v 17.3.0 on macOS

### Issue description

in the `gateway.paymentMethod.update()` call, when passing in options, `verificationAmount` is misspelled as `verificationAcmount`

**Comment by scannillo** [comment]
Hi @andrescamperi - I don't see this misspelling anywhere in the SDK. Can you provide a link to where you notice this?

**Comment by andrescamperi** [comment]
Hi - apologies, the typo is in the @types/braintree package. closing this issue
