### ISSUE TITLE
Braintree Node.js library link is down/not working

### ISSUE THREAD

**Issue by ryan-efendy** [braintree/braintree_node#202]
The link to the Braintree Node.js library is down/not working: https://developers.braintreepayments.com/node/sdk/server/overview

![image](https://user-images.githubusercontent.com/12979345/140553753-28b8de7d-f8cf-43cb-a373-1f00c0cc1c2e.png)

**Comment by jplukarski** [comment]
The updated link should be https://developer.paypal.com/braintree/docs/start/hello-server/node

The links in this repo have been updated

**Comment by ryan-efendy** [comment]
@jplukarski the braintree nodejs sdk is different than the getting started doc. Can you link us to the braintree nodejs SDK doc?
