### ISSUE TITLE
The doc routes to the getting started guide not api docs?

### ISSUE THREAD

**Issue by ryan-efendy** [braintree/braintree_node#203]
The braintree nodejs sdk doc is different than the getting started doc. Can link us to the braintree nodejs SDK doc, and not the get started guide?

**Comment by hollabaq86** [comment]
👋  @ryan-efendy sorry for the delay, can you clarify which URLs you mean, and where you're seeing the incorrect link?

**Comment by hollabaq86** [comment]
Closing this since we need more info. If anyone encounters a similar issue, please make a new issue with details on URLs (and where you see these hyperlinks) that are incorrect.
