### ISSUE TITLE
Account is not showing verified by Network check. Always show not verified in sandbox mode.

### ISSUE THREAD

**Issue by kwanso-aleem** [braintree/braintree_node#207]
### General information

- SDK/Library version: node: 3.11.0 
- Environment:  Sandbox  
- Language, language version, and OS: Node v14.19.0 on Ubuntu 20 LTS 

### Issue description

When I used PaymentMethod.Create with a nonce. It returned verified false & verifications empty array. Can you please guide me or provide me with a testing account with verified status. Thanks!

bank details
{ accountNumber: '1000000000',
      routingNumber: '011000015',
      accountType: 'savings',
      ownershipType: "personal",
      firstName: "John",
      lastName: "Doe",
      billingAddress: {
        streetAddress: '123 Fake St',
        locality: 'San Francisco',
        region: "CA",
        postalCode: "94119"
      }
}

**Comment by crookedneighbor** [comment]
Reach out to our support team for assistance with this: https://developer.paypal.com/braintree/help
