### ISSUE TITLE
Cannot use "usBankAccountVerificationMethod" method in options field while using PaymentMethod for ACH Direct Debit

### ISSUE THREAD

**Issue by darshil-vt** [braintree/braintree_node#223]
gateway.paymentMethod.create({
customerId: "131866",
paymentMethodNonce: nonceFromTheClient,
options: {
usBankAccountVerificationMethod: braintree.UsBankAccountVerification.VerificationMethod.NetworkCheck // or MicroTransfers or IndependentCheck
}
![Screenshot 2023-05-10 172657](https://github.com/braintree/braintree_node/assets/119478516/d82b5cdb-98e4-4edc-a5f2-3e7e9a4c5f0c)

Documentation is shows that paymentMethod can use this method but npm package has no method specified in it and it gives error.

**Comment by darshil-vt** [comment]
@hollabaq86 Thank you for replying,

I am trying to integrate the ACH Direct Debit payment system in our NodeJS project and We have to implement it in a live website on customer demand. 
I was referring this link of Braintree's developer site: https://developer.paypal.com/braintree/docs/guides/ach/server-side and shows me that payment method's create function has options field and it can use "usBankAccountVerificationMethod" but when i was try to use it in NodeJS it gives me error and i was using npm's package braintree, i checked that package's documentation but it also didn't has "usBankAccountVerificationMethod" method in options field.

**Comment by hollabaq86** [comment]
I'm going to go ahead and close this since I haven't gotten any updates, but I believe the root is a third party types library is missing these parameters.
