### ISSUE TITLE
Searching transactions by date is insufficiently documented, missing syntax and minutes-vs-seconds precision

### ISSUE THREAD

**Issue by dlopuch** [braintree/braintree_node#36]
It would be helpful if the node [transaction search documentation](https://developers.braintreepayments.com/javascript+node/reference/general/searching/search-fields#range-fields) included what the valid range fields are, specifically createdAt, updatedAt, etc.  It seems the only reference for what you can search by is by looking at the code itself.

Additionally, the acceptable syntax is missing, specifically the potentially-important detail that search is sensitive down to minute precision while transactions are *reported with* seconds precision.

For example:

```javascript
function searchTransactionsOnOrBefore(createdAtQuery) {

  console.log("Getting transactions on or before createdAt: " + createdAtQuery);

  var transactionsStream = gateway.transaction.search(function(search) {
    search.createdAt().max(createdAtQuery);
  });

  var expectedMaxDate = new Date(createdAtQuery),
      countBadTransactions = 0;

  transactionsStream.on('data', function(tx) {
    if ( (new Date(tx.createdAt)) > expectedMaxDate) {
      console.log('BAD #' + (countBadTransactions++),
                  'got a transaction created AFTER expected max date: ', tx.createdAt);
    } else {
      console.log('Now seeing transactions at or below max date, done.');
      transactionsStream.pause();

      if (countBadTransactions)
        console.log("ERROR: SAW " + countBadTransactions + " created AFTER specified max date!");

    }
  });
};
```

In my sandbox, I have a lot of transactions created close together (within a second or two).

An example transaction out of the library looks like:

```javascript
{ id: 'fy5bqw',                           
  status: 'settled',                      
  type: 'sale',                           
  currencyIsoCode: 'USD',                 
  amount: '1071.91',                      
  merchantAccountId: 'hfjjdfd2zvkq25yr',  
  orderId: null,                          
  createdAt: '2014-10-03T23:15:00Z',      
  updatedAt: '2014-10-03T23:18:00Z',      
  ...                                     
}                                         
```

Okay, lets feed the exact createdAt value back into the library:

```
> searchTransactionsOnOrBefore( '2014-10-03T23:15:00Z' )
Getting transactions on or before createdAt: 2014-10-03T23:15:00Z
BAD #0 got a transaction created AFTER expected max date:  2014-10-03T23:15:59Z
...
BAD #70 got a transaction created AFTER expected max date:  2014-10-03T23:15:45Z
...
BAD #126 got a transaction created AFTER expected max date:  2014-10-03T23:15:30Z
...
BAD #207 got a transaction created AFTER expected max date:  2014-10-03T23:15:15Z
...
BAD #265 got a transaction created AFTER expected max date:  2014-10-03T23:15:01Z
Now seeing transactions at or below max date, done.
ERROR: SAW 266 created AFTER specified max date!
```

Admittedly in a lot of cases the seconds-vs-minute precision doesn't matter, but well, I found this behavior because in my use-case it does.  

At the very least, acceptable syntax and precision notes should be documented.

**Comment by gileze33** [comment]
+1 I have exactly the same problem - did you ever come to a solution?

**Comment by dlopuch** [comment]
Nothing beyond in-memory filtering outside of the braintree lib.

**Comment by chrissiedeist** [comment]
Thanks for this input! I’m a developer at braintree, so I'll run this by our docs team and look into getting this changed.

**Comment by chrissiedeist** [comment]
We've added examples and a clarifying comment to the documentation; these changes will do out in the next release.
