### ISSUE TITLE
Incomplete API Support

### ISSUE THREAD

**Issue by coreybutler** [braintree/braintree_node#40]
Is there a roadmap or some sort of indicator of when the non-supported API functionality will be supported in the node module? For example, there are a number of pages in the documentation (like [the plan page](https://developers.braintreepayments.com/ios+node/sdk/server/recurring-billing/plans)) that indicate certain functionality is not available. This kind of sucks... we have to use at least two different approaches for complete interaction with the API.

**Comment by dewyze** [comment]
@coreybutler Closing this issue since plan has been added to the node library. Thanks again for letting us know.
