### ISSUE TITLE
Customer.paymentMethods not populated

### ISSUE THREAD

**Issue by alawong** [braintree/braintree_node#46]
1) If I create a customer -> create a payment method with the nonce and attach to created customer -> then paymentMethods is set (expected)

Result:
customer.creditcard : [creditcard obj]
customer.paymentMethods : [creditcard obj]

2) If I create a customer with payment method nonce -> then paymentMethods not set.

Result:
customer.creditcard : [creditcard obj]
customer.paymentMethods: null

Shouldn't both yield the same result?

**Comment by ryanjpodonnell** [comment]
Nice catch @alawong,

We think we understand why `customer.paymentMethods` was empty and are working on a fix. We should have this repaired on our next release. Thanks for pointing this out to us!

Ryan
Braintree Developer

**Comment by ryanjpodonnell** [comment]
Hello @alawong,

We updated our [customer class](https://github.com/braintree/braintree_node/blob/4c7bbb54ae2326c178d01849bf5a76d4864f7c4b/src/braintree/customer.coffee) so now the customer's `paymentMethods` will behave as intended.
