### ISSUE TITLE
Transaction with invalid Merchant account yields a null result object

### ISSUE THREAD

**Issue by alawong** [braintree/braintree_node#47]
```javascript
gateway.transaction.sale({
    amount: total,
    merchantAccountId: <INVALID/NON EXISTENT>,
    paymentMethodNonce: nonce,
    serviceFeeAmount: service
  }, function (err, result) {
    console.log(result);
});
```

Should this be returning a proper result object with success = false, and a proper error message?

I.e
91513 – Merchant account ID is invalid. If you specify the merchant account ID to use to process a transaction and it does not match any of your merchant accounts, you'll get this error.
[Docs](https://developers.braintreepayments.com/javascript+ruby/sdk/server/transaction-processing/validations)

**Comment by wjr1985** [comment]
Hi alawong,

Thanks for bringing this to our attention. It looks like we return an Authorization Error in response to an invalid or nonexistent Merchant Account ID. When this happens, the result object will be `nil`, and the `err` object will be populated with `braintree.errorTypes.authorizationError`. We'll make sure to update our documentation to reflect this.

Thanks,

Bill
Braintree Developer

**Comment by dewyze** [comment]
@alawong Closing this issue, if initial answer didn't address your issue feel free to reopen.
