### ISSUE TITLE
create nonce on server

### ISSUE THREAD

**Issue by robrichard** [braintree/braintree_node#48]
Is it possible to create the payment method nonce using the node api? I want to do this for our testing framework.

**Comment by robrichard** [comment]
I've tried using braintree-web with jsdom, but it looks like window.postmessage is not supported by jsdom.

**Comment by openbl** [comment]
@robrichard,

We do have [static, fake payment method nonces](https://developers.braintreepayments.com/reference/general/testing#payment-method-nonces) that can be used for testing in our sandbox environment. We currently don't have a way to generate your own testing nonces in sandbox although that would be a great enhancement.

**Comment by dewyze** [comment]
@robrichard Closing this issue. Feel free to reopen if you have further questions.
