### ISSUE TITLE
There are never transactions when generating a sample webhook notification for SubscriptionChargedSuccessfully

### ISSUE THREAD

**Issue by loudwinston** [braintree/braintree_node#49]
This is effectively a clone of the same issue for the Ruby library (https://github.com/braintree/braintree_ruby/issues/64).  Overall I find the documentation lacking in example responses in many places, but this is one specifically that I am currently dealing with.

Knowing how much the user was charged can be a key reason for consuming a webhook notification for SubscriptionChargedSuccessfully (i.e. tracking revenue per use internally).

When generating a sample webhook notification for this using webhookTesting - a subscription comes back with the webhook payload, but no transactions are ever a part of that webhook.

This subscription within the notification payload should contain a fake Transaction that includes a charged amount.

**Comment by raymondberg** [comment]
@loudwinston  Thanks for your recommendation! We're going to push this in an upcoming release.

**Comment by GustavoLent** [comment]
The docs still with a lack of information in the examples of notifications...
