### ISSUE TITLE
Exposing Request/Response Objects

### ISSUE THREAD

**Issue by trainerbill** [braintree/braintree_node#51]
I am looking for a way to expose the request and response objects for each api call.  I want to be able to validate the object against it and return all the available attributes for a call.  Wondering if you could add this functionality to the SDK.

**Comment by raymondberg** [comment]
I'm not sure what you mean, @trainerbill. Could you provide more detail, examples or pseudocode to explain your issue?

**Comment by dewyze** [comment]
@trainerbill Closing this for now, feel free to reopen if you have further questions.
