### ISSUE TITLE
Missing maestro card logo?

### ISSUE THREAD

**Issue by sogko** [braintree/braintree_node#52]
![screen shot 2015-04-20 at 12 35 20 am](https://cloud.githubusercontent.com/assets/78585/7220326/b540696a-e6f5-11e4-9460-548f71bdd2ec.png)

I was testing out different cards on sandbox and while iterating through a customer's payment methods from the API, I noticed that a maestro card ```imageUrl``` points to a 404 url: https://assets.braintreegateway.com/payment_method_logo/maestro.png?environment=sandbox

This issue doesn't show up on drop-ui (the dropui somehow knows not to show a card image for maestro cards).

Thanks!

**Comment by kyledetella** [comment]
@sogko thanks for bringing this up! We are working on a fix now.

**Comment by kyledetella** [comment]
@sogko thanks for bringing this up. The Maestro image is now available.

![Maestro](https://assets.braintreegateway.com/payment_method_logo/maestro.png?environment=sandbox)
