### ISSUE TITLE
downForMaintenanceError: Down for Maintenance

### ISSUE THREAD

**Issue by pbshop1001** [braintree/braintree_node#53]
I test following stream from sandbox. 

var today = new Date();
var stream = gateway.transaction.search(function (search) {
  search.createdAt().min(today.getDate() - 1);
});

but it keeps giving me 'downForMaintenanceError: Down for Maintenance' error.

**Comment by wjr1985** [comment]
Hi @pbshop1001,

I just tried to reproduce this and have not seen the `downForMaintenanceError` that you've received. If you're still seeing this error, I recommend contacting us via email (support@braintreepayments.com) so we can take a more in-depth look at this issue.

Best,
Bill
