### ISSUE TITLE
what is "MerchantAccount.FundingDestination.Bank"?

### ISSUE THREAD

**Issue by jamesbondo** [braintree/braintree_node#63]
I wasn't trying to create a marketplace merchant, but there's this unknown variable. 

merchantAccountParams = {
  individual: {
    firstName: "Jane",
    lastName: "Doe",
    email: "jane@14ladders.com",
    phone: "5553334444",
    dateOfBirth: "1981-11-19",
    ssn: "456-45-4567",
    address: {
      streetAddress: "111 Main St",
      locality: "Chicago",
      region: "IL",
      postalCode: "60622"
    }
  },
  business: {
    legalName: "Jane's Ladders",
    dbaName: "Jane's Ladders",
    taxId: "98-7654321",
    address: {
      streetAddress: "111 Main St",
      locality: "Chicago",
      region: "IL",
      postalCode: "60622"
    }
  },
  funding: {
    descriptor: "Blue Ladders",
    destination: MerchantAccount.FundingDestination.Bank,
    email: "funding@blueladders.com",
    mobilePhone: "5555555555",
    accountNumber: "1123581321",
    routingNumber: "071101307"
  },
  tosAccepted: true,
  masterMerchantAccountId: "14ladders_marketplace",
  id: "blue_ladders_store"
};

gateway.merchantAccount.create(merchantAccountParams, function (err, result) {
});

**Comment by matthewarkin** [comment]
Merchant accounts can receive their funds multiple ways, either via a bank account deposit, or via a transfer to their venmo account.

For a deposit to their bank account, you'd set the funding destination to Bank, for a deposit via venmo, you'd set it to email or mobile phone. 

For additional information see https://developers.braintreepayments.com/reference/request/merchant-account/create/node#funding.destination

**Comment by jamesbondo** [comment]
hm.. thanks a lot!

**Comment by jdlc** [comment]
Thanks for answering, @matthewarkin. Closing this issue.

**Comment by XiSmartElf** [comment]
But ...
destination: MerchantAccount.FundingDestination.Bank,
MerchantAccount is undefined in js.. I tried just put 'bank' but it failed by asking me for individual parameters

Any clue?

Thanks!
