### ISSUE TITLE
Can't immediately proceed with payment using nonce, created by braintree widget

### ISSUE THREAD

**Issue by smashercosmo** [braintree/braintree_node#64]
When I receive paymentMethodNonce from braintree widget, I use it first to create a customer and then to make an actual payment. But while creating customer is successful, making a payment causes an error "Payment method nonce is invalid". Previously it was possible. Is it an intended behaviour or a bug?

P.S. Didn't know where to post it, to braintree_node or braintree_web

**Comment by matthewarkin** [comment]
It sounds like you're using the nonce twice? Once to create the customer and then specifying the nonce again when you're creating the charge?

The nonce should only be used once, so when you create the customer, then when you create the charge you'd only specify the customer id and optionally the paymentMethodToken of their vaulted card data

**Comment by smashercosmo** [comment]
Yes, I'm trying to use paymentMethodNonce twice: first to create a customer and then to create a subscription for this customer. I remember, it was working before.
> then when you create the charge you'd only specify the customer id
You can't specify customer id when creating subscription (according to documentation). You can only specify planId and either token or nonce.
So, what you are trying to say is that I should you payment method token first time I create a customer. This token should be extracted from the customer data. But next time, when braintree widget is initialized with already selected payment method, I should use payment method nonce, generated by widget?

**Comment by matthewarkin** [comment]
When you get a nonce and save it to a customer, the API will automatically create a token (that should be returned as part of the customer object). You can then use that token when you create the subscription or create a charge.

**Comment by smashercosmo** [comment]
Yes, but next time (when customer is already created), I go to the braintree widget and see already selected payment method. Should I somehow load customer data and use token again or I can just use nonce, generated by widget?

**Comment by matthewarkin** [comment]
Yeah, support@braintreepayments.com may be aware of best / common practices in this area. As I don't necessarily know how the linkage of customer to subscription would work via the API if you used a new nonce as opposed to a token.

**Comment by smashercosmo** [comment]
Ok, thx, I'll write them
