### ISSUE TITLE
add ability to get AddOns

### ISSUE THREAD

**Issue by legikaloz** [braintree/braintree_node#66]
It would be nice to implement this in node.js lib too:
https://developers.braintreepayments.com/reference/request/add-on/all/node

**Comment by crookedneighbor** [comment]
Thanks for the feedback. We're looking into adding this functionality to the module.

**Comment by omgrr** [comment]
@legikaloz We added this feature in `1.37.0`. Let us know if you run into any issues and thanks for bringing this to our attention!
