### ISSUE TITLE
Question: ErrorResponse in result on transaction with invalid format

### ISSUE THREAD

**Issue by renarsvilnis** [braintree/braintree_node#68]
Hi,
while developing a project made a sandbox transaction for `NaN` amount (had a mistake in calculating total). The transaction callback didn't return an `error`, but had an `ErrorResponse` instance within the `result` of the callback instead of `error`.

**Just wondering is it an normal behaviour?** Because I'd expect that to be as an error.

```javascript
// ...

// 💵 💵 💵 bills y'all!
gateway.transaction.sale({
  amount: values.totalPrice.toString(), // given NaN by mistake
  paymentMethodNonce: nonce.toString(),
  options: {
    submitForSettlement: true
  }
}, function (err, result) {

  console.log(err);
  // null

  console.log(res);
  // ErrorResponse {
  //   errors:
  //    ValidationErrorsCollection {
  //      validationErrors: {},
  //      errorCollections: { transaction: [Object] } },
  //   params:
  //    { transaction:
  //       { amount: 'NaN',
  //         paymentMethodNonce: 'dace29gsagad-gas327-4c32-bgasda-2fedfdfahak2a98',
  //         options: [Object],
  //         type: 'sale' } },
  //   message: 'Amount is an invalid format.',
  //   success: false }

  if (err) { // err doesn't get triggered
    return transaction.rollback(err);
  }

  // handle successful transaction
  // ...
});
```

**Comment by matthewarkin** [comment]
That is expected https://developers.braintreepayments.com/reference/general/validation-errors/overview/node

err would get set if there was some sort of exception https://developers.braintreepayments.com/reference/general/exceptions/node

**Comment by renarsvilnis** [comment]
Thanks for clarifying :+1:
