### ISSUE TITLE
Cannot determine if customer payment method is instance of PayPal

### ISSUE THREAD

**Issue by marcuspoehls** [braintree/braintree_node#71]
There seem to be an issue when trying to check the instance of customer’s payment method against PayPal.

We try to determine if the account is either `CreditCard` or `PayPalAccount` following the [reference guide](https://developers.braintreepayments.com/reference/response/payment-method/node#determine-payment-method-type). 

When using this snippet:

```
var paymentMethod = customer.paymentMethods[ 0 ]
var isPayPal = paymentMethod instanceof braintree.PayPalAccount
```

there’s always the following error:

```
Expecting a function in instanceof check, but got undefined
```

We use this lib in version `1.35.1`.

**Comment by jdlc** [comment]
@marcuspoehls,

Thanks for reporting this to us! Only the snippet shown on the docs page, `paymentMethod instanceof braintree.CreditCard` currently works. We will look into adding functionality so that other payment method types can be identified in a similar fashion, and reword the docs to make this explicit.

**Comment by marcuspoehls** [comment]
@jdlc Thanks for the info! Would be great if you can add the functionality to add the check for further payment methods besides credit card. I’m not familiar with CoffeeScript, that’s what keeps me from offering help with the implementation. Hope to hear from you soon :)

**Comment by kexline4710** [comment]
@marcuspoehls
​
Our latest release (1.37.1) contains the functionality to check the instance of many payment method types including `PayPalAccount`’s. We will update our documentation soon to include additional examples of how you can use this. Thank you for bringing this to our attention!

**Comment by marcuspoehls** [comment]
@jdlc @kexline4710 Awesome! Thanks a lot!
