### ISSUE TITLE
Error installing module

### ISSUE THREAD

**Issue by samundrak** [braintree/braintree_node#72]
Facing error while installing module , it says 

`Refusing to install braintree as a dependency of itself`

Node -v is=` v5.8.0`
Npm -v is  = `v3.7.3`

**Comment by NickTomlin** [comment]
I am able to install `braintree` using node `5.8.0` without any issues. Would you mind sharing the relevant parts of your `package.json`?

I'd also double check that the `name` property in your `package.json` is not also `braintree` which would be one possible source of this issue.

**Comment by samundrak** [comment]
at first i didn't sort the problem and then i just forked this repo and compiled coffee codes and then imported it to my project and it worked but late i came to know app i created and this module name got conflict so i saw this error. Thanks my problem is solved

**Comment by NickTomlin** [comment]
@samundrak Glad you figured it out! Thanks for checking back in :smile:
