### ISSUE TITLE
getaway.transaction.sale does not check if ids are strings

### ISSUE THREAD

**Issue by simonepri** [braintree/braintree_node#73]
The node SDK does not check if we pass invalid arguments into some fields while creating a new transaction.
For istance:

```
var anInvalidOrderId = {};
var options = {
    orderId: anInvalidOrderId,
    amount: '5.00',
    paymentMethodNonce: "nonce-from-the-client",
    options: {
         submitForSettlement: true
     }
};
gateway.transaction.sale(options, function (err, result) {});
```

Will throw:
**Uncaught exception
stack: TypeError: Cannot read property 'apiErrorResponse' of undefined**

Here is the stacktrace:

>at C:\~\node_modules\braintree\lib\braintree\gateway.js:23:19
at C:\~\node_modules\braintree\lib\braintree\http.js:103:20
at Parser.<anonymous> (C:\~\node_modules\xml2js\lib\xml2js.js:138:18)
at emitOne (events.js:90:13)
at Parser.emit (events.js:182:7)
at Object.saxParser.onerror (C:\~\node_modules\xml2js\lib\xml2js.js:51:24)
at emit (C:\~\node_modules\sax\lib\sax.js:639:35)
at error (C:\~\node_modules\sax\lib\sax.js:668:5)
at strictFail (C:\~\node_modules\sax\lib\sax.js:692:7)
at Object.write (C:\~\node_modules\sax\lib\sax.js:1091:13)
at Parser.exports.Parser.Parser.parseString (C:\~\node_modules\xml2js\lib\xml2js.js:145:29)
at Parser.parseString (C:\~\node_modules\xml2js\lib\xml2js.js:3:63)
at IncomingMessage.<anonymous> (C:\~\node_modules\braintree\lib\braintree\http.js:102:31)
at emitNone (events.js:85:20)
at IncomingMessage.emit (events.js:179:7)
at endReadableNT (_stream_readable.js:913:12)

This also happen with customer id and other fields.

Simone

**Comment by simonepri** [comment]
Same behaviour by passing invalid customerId to **_gateway.clientToken.generate_**:
```
var anInvalidCustomerId = {};
var options = {
    customerId: anInvalidOrderId,
};
gateway.clientToken.generate(options, function(err, res) {});
```

> stack: TypeError: Cannot read property 'clientToken' of undefined
at C:\~\node_modules\braintree\lib\braintree\client_token_gateway.js:70:19
at C:\~\node_modules\braintree\lib\braintree\http.js:103:20
at Parser.<anonymous> (C:\~\node_modules\xml2js\lib\xml2js.js:138:18)
at emitOne (events.js:90:13)
at Parser.emit (events.js:182:7)
at Object.saxParser.onerror (C:\~\node_modules\xml2js\lib\xml2js.js:51:24)
at emit (C:\~\node_modules\sax\lib\sax.js:639:35)
at error (C:\~\node_modules\sax\lib\sax.js:668:5)
at strictFail (C:\~\node_modules\sax\lib\sax.js:692:7)
at Object.write (C:\~\node_modules\sax\lib\sax.js:1091:13)
at Parser.exports.Parser.Parser.parseString (C:\~\node_modules\xml2js\lib\xml2js.js:145:29)
at Parser.parseString (C:\~\node_modules\xml2js\lib\xml2js.js:3:63)
at IncomingMessage.<anonymous> (C:\~\node_modules\braintree\lib\braintree\http.js:102:31)
at emitNone (events.js:85:20)
at IncomingMessage.emit (events.js:179:7)
at endReadableNT (_stream_readable.js:913:12)

**Comment by kexline4710** [comment]
I was unable to recreate these exceptions by passing invalid content in the `customerId` option for client token generation or the `orderId` option for a transaction sale.
​
However, I *was* able to recreate the exception `TypeError: Cannot read property 'clientToken' of undefined`, by misconfiguring the gateway object so that is undefined. 
​
Is your gateway properly configured and required in all of the necessary areas? Also, what version of the library are you using?

**Comment by matthewarkin** [comment]
This looks really similar to https://github.com/braintree/braintree_node/issues/69 where passing objects instead of strings causes some issue in processing the response.

**Comment by simonepri** [comment]
@matthewarkin is exactly the same peoblem i had, obviously with a MongoDB Object ID we can just convert it to string and all goes fine.
But the point is that braintree internal api should answer with an error to the node sdk when invalid argument are passed.

**Comment by kexline4710** [comment]
Ah, I see. We will take some time to investigate and see if there is a way to accomplish this without breaking backwards compatibility.

**Comment by matthewarkin** [comment]
This is an asynchronous error (it happens when parsing the response from Braintree), so its a bit of improper Node style to have this throw an exception. The proper thing I believe (and per https://developers.braintreepayments.com/reference/general/exceptions/node) would be to return (at a minimum a unexpectedError) or a validation error (https://developers.braintreepayments.com/reference/general/validation-errors/overview/node -- I believe this is a client side check but I'll admit I haven't read the coffeescript well enough).

Even its a backwards incompatible change, I'd argue that the old behavior was a bug since the Node library should not be returning exceptions in an undocumented manor.

**Comment by simonepri** [comment]
The problem could also be resolved client side by just check if the response object is not empty.
```
if(response)
//do things
else
//throw an error
```

**Comment by tom-shani** [comment]
+1

I am also getting the `'apiErrorResponse' of undefined` error when passing a non-string version of a mongo _id.

**Comment by jdlc** [comment]
@simonepri @tom-shani
We haven't been able to recreate this error passing in a MongoDB ObjectID. Can you let us know what version of Node.js and the Braintree client library you are using? Thanks!

**Comment by tom-shani** [comment]
@jdlc I'm running node v5.9.0 and braintree-node 1.37.1

**Comment by tom-shani** [comment]
@jdlc [This gist](https://gist.github.com/tom-shani/9c14e2d446f83d7d58f57f6b4b2636fc) should reproduce the error for you

**Comment by raymondberg** [comment]
@tom-shani and @simonepri, We're able to reproduce with your example, and it looks like we're less restrictive than we could be in this case. We may add some checks to strip out some of these more complex datatypes outright, but the basic remediation is to follow the type specification in the documentation. These [different](https://developers.braintreepayments.com/reference/request/client-token/generate/node#customer_id) [values](https://developers.braintreepayments.com/reference/request/transaction/sale/node#order_id) should be only string types and anything else will act unpredictable and likely will fail.
