### ISSUE TITLE
504 error on gateway.customer.find()

### ISSUE THREAD

**Issue by eahenke** [braintree/braintree_node#74]
I'm consistently getting a 504 timeout error when calling gateway.customer.find() from my local development environment. No other methods cause this problem. Everything seems to work fine on the production server, however.
Here's the error/stacktrace:
```{
  "error": {
    "name": "unexpectedError",
    "status": 500,
    "message": "Unexpected HTTP response: 504",
    "type": "unexpectedError",
    "stack": "unexpectedError: Unexpected HTTP response: 504\n    at Object.UnexpectedError (/.../node_modules/braintree/lib/braintree/exceptions.js:10:11)\n    at Http.checkHttpStatus (/.../node_modules/braintree/lib/braintree/http.js:47:27)\n    at IncomingMessage.<anonymous> (/.../node_modules/braintree/lib/braintree/http.js:95:23)\n    at Object.forward (/usr/local/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:79:23)\n    at IncomingMessage.eval (eval at wrap (/usr/local/lib/node_modules/strongloop/node_modules/strong-agent/lib/proxy.js:201:20), <anonymous>:3:21)\n    at emitNone (events.js:72:20)\n    at IncomingMessage.emit (events.js:166:7)\n    at endReadableNT (_stream_readable.js:905:12)\n    at /.../node_modules/async-listener/glue.js:188:31\n    at nextTickCallbackWith2Args (node.js:474:9)\n    at process._tickDomainCallback (node.js:429:17)\n    at process.fallback (/.../node_modules/async-listener/index.js:450:15)"
  }
}```

Any ideas?  Thanks.

**Comment by jdlc** [comment]
The 504 error code indicates that the gateway timed out while trying to process your request. 
The sandbox environment does not have the same performance standards as production, which may be why you are only seeing this problem in your development environment. Are you using version 1.37.0 or greater of the Node client library and [configuring the timeout to be shorter than the default 60 seconds](https://developers.braintreepayments.com/reference/general/best-practices/node#timeouts)?

If you reach out to [Braintree support](https://support.braintreepayments.com) they can help track down your specific issue to provide greater insight.
