### ISSUE TITLE
Callback fired twice in src/braintree/http.coffee

### ISSUE THREAD

**Issue by wlaurance** [braintree/braintree_node#76]
Yesterday I had an issue where the callback in http.coffee fires twice.

https://github.com/braintree/braintree_node/blob/master/src/braintree/http.coffee#L59-L91

One callback happens when the http client's `setTimeout` function fires. The other happens in the error event handler when the socket closes.

Should this library be responsible for firing the callback only once?

I noticed there is a non running test here, https://github.com/braintree/braintree_node/blob/master/spec/integration/braintree/http_spec.coffee#L52-L64

Has anyone else experienced the double callback?

**Comment by iboneva** [comment]
Hey @wlaurance

We looked into this today and this does seem to be an issue. We're going to look into this further.

**Comment by iboneva** [comment]
Hey @wlaurance

The callback should not be firing twice. We have a fix for this issue and I will let you know once it is released.

**Comment by wlaurance** [comment]
Hey @iboneva Thanks! sounds good

**Comment by ragulka** [comment]
Hi, I am just experiencing the same in a production app, and it's wreaking all sorts of havoc. Hope the fix will be deployed soon!

**Comment by raymondberg** [comment]
Changes to address this have been released in `1.38.0`. Closing for now, but feel free to reopen if this does not address the issue. https://github.com/braintree/braintree_node/commit/c74ae1210a7437d4955fd33d3fb1f6811a98f39c

Thanks for reporting this, @wlaurance!

**Comment by wlaurance** [comment]
You're welcome! And thanks for the fix! 👍
