### ISSUE TITLE
Callback responses

### ISSUE THREAD

**Issue by stwiname** [braintree/braintree_node#78]
I'm trying to create Typescript definitions for this library but the docs seem to have a few holes.

It is far from complete at this stage but this is what I have so far: 
https://gist.github.com/stwiname/a455abc0947b16a60301244b8cf0c7d5

The biggest trouble I am having is deciphering the callback response objects. Some responses return the wanted object while others return an object with `success`, `message` and an object (eg. transaction). 

I am also aware that search responses return an object with an `each` function.  But does it have any other properties on it? 

Any clarification would be appreciated

**Comment by pblesi** [comment]
Hi @stwiname 

This is our documentation on handling search results via our API in Node: https://developers.braintreepayments.com/reference/general/searching/search-results/node

`each` is the recommended process for iterating over the search results. There are no other properties on this object that are part of our API.
 
I am closing this issue, but if you need further clarification, feel free to reopen it.
