### ISSUE TITLE
Remove/Delete sub-merchant account (marketplace)

### ISSUE THREAD

**Issue by XiSmartElf** [braintree/braintree_node#79]
Does anyway know how to remove an existing created submerchant account? either through the UI or programatically?

Thanks!

**Comment by XiSmartElf** [comment]
up

**Comment by xionon** [comment]
@XiSmartElf We actually don't support deleting submerchants. You should instead just suspend the submerchant and stop using it.

**Comment by XiSmartElf** [comment]
let's say all my user has a submerchant account that i would like to split the fee to, is there a maxium number fo submerchant accounts I can create?

**Comment by matthewarkin** [comment]
I do not believe there is, but this is more a question for support as it is not an issue with the Node API. I'd recommend contacting support via support@braintreepayments.com or https://www.braintreepayments.com/contact

**Comment by XiSmartElf** [comment]
I see thank you!
