### ISSUE TITLE
ClientToken.generate()  - Invalid Keys

### ISSUE THREAD

**Issue by jamesdixon** [braintree/braintree_node#81]
Hi,

The [documentation](https://developers.braintreepayments.com/reference/request/client-token/generate/node) specifies that `failOnDuplicatePaymentMethod` and `makeDefault` are valid options  when generating a `ClientToken`. However, when submitting those options, I get the following error:

`unexpectedError: Invalid keys: makeDefault,failOnDuplicatePaymentMethod`

Here's my code:

```js
        const options = {
            customerId: customerId,
            options: {
                failOnDuplicatePaymentMethod: true,
                makeDefault: true
            }
        };

        return new Promise((resolve, reject) => {

            Gateway.clientToken.generate(options, (err, result) => {

                if (!result.success) {
                    reject(new Error(result.message));
                }

                resolve(result);
            });
        });
```

I also tried moving these two params out of the `options` hash and I get an `authorizationError`, which seems to be the incorrect error.

Thanks!
James

**Comment by crookedneighbor** [comment]
I am unable to reproduce the error. What version of the Braintree module are you using?

**Comment by crookedneighbor** [comment]
Okay, I _can_ reproduce the error if customerId is undefined. Those options only apply if a customer id exists. Best guess is that your `customerId` variable is not always defined. 

See https://github.com/braintree/braintree_node/blob/fcb5cd661344b557cf8a51c75f3f18380c3ca482/src/braintree/client_token_gateway.coffee#L21-L30 for reference.

**Comment by jamesdixon** [comment]
@crookedneighbor that was the issue. I'm using the same method to generate the token for cases where there is or is not a `customerId`. Thanks!
