### ISSUE TITLE
Request - Add ability to get all discounts

### ISSUE THREAD

**Issue by zerefel** [braintree/braintree_node#82]
It would be nice to have the ability to fetch all discount objects using the node.js module.
https://developers.braintreepayments.com/reference/request/discount/all/node

**Comment by jackellenberger** [comment]
Hi @zerefel,

This is our mistake, we implemented discount.all() in version 1.40.0 but have not updated the docs to reflect that. 

In the mean time, you can run `discounts = gateway.discount.all(function (err, result) {});`

Expect to see the docs updated soon.

**Comment by zerefel** [comment]
@jackellenberger Thank you for the timely response! It works like a charm.
