### ISSUE TITLE
Any way to charge the master merchant account?

### ISSUE THREAD

**Issue by XiSmartElf** [braintree/braintree_node#83]
I want to charge the master merchant account and give the money to submerchant so i don't need to use a payment token

**Comment by jackellenberger** [comment]
Hi @XiSmartElf,

I'm not sure I understand what you'd like to do. If you're looking for a way to transfer funds from a master merchant's bank directly to a submerchant's, that is unfortunately not possible. 

Let me know if I've misunderstood, you might also contact [support](support@braintreepayments.com) to share details about your specific use case.

**Comment by jackellenberger** [comment]
I'm going to close this issue, feel free to follow up if you have more questions or if I misunderstood your situation.
