### ISSUE TITLE
I encounter this error after NPM Start

### ISSUE THREAD

**Issue by kevinlee85** [braintree/braintree_node#85]
Linux 3.13.0-48-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.7
npm ERR! code ELIFECYCLE
npm ERR! cf-bt-client-sdk-node@0.0.1 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cf-bt-client-sdk-node@0.0.1 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cf-bt-client-sdk-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cf-bt-client-sdk-node
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cf-bt-client-sdk-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/justinspot/justinspot_nodejs/npm-debug.log

**Comment by jdlc** [comment]
We do not maintain the node-braintree-demo (cf-bt-client-sdk-node) hosted [here](https://github.com/jeffprestes/node-braintree-demo).

If you would like to try using Braintree with node, I would suggest our [official Express example](https://github.com/braintree/braintree_express_example).
