### ISSUE TITLE
is payment token fixed for the payment method forever

### ISSUE THREAD

**Issue by XiSmartElf** [braintree/braintree_node#89]
i saved a payment to master submerchant account, i use the hardcoded payment token everytime to charge master merchant account, wondering will the payment token change somehow? if yes, what's the best way to charge the payment method

**Comment by danakatz** [comment]
Hi @XiSmartElf - the payment token shouldn't change, so the workflow you describe will work just fine. Please reach out to [Braintree support](mailto:support@braintreepayments.com) with any other questions about your integration!
