### ISSUE TITLE
Source maps failed to load.

### ISSUE THREAD

**Issue by Andreyco** [braintree/braintree_node#91]
After install from `npm` registry, package fails to load.

**Issues:**
- source maps are not generated
- deprecated source mapping annotations are used

**Setup:**
- macOS
- Node 7.4.0
- installed with npm (and yarn as well)

**Comment by crookedneighbor** [comment]
Can you be more descriptive with what's happening when you say the package fails to load?

I'm able to install and use it just fine with `node@7`, `npm@4` on Mac OSx 10.12.2.

```
$ npm i braintree
$ node -r braintree
> let b = require('braintree')
> b
// the braintree object
```

**Comment by Andreyco** [comment]
Found out this has something to do with running app with [devtool](https://github.com/Jam3/devtool).  

<details>
    <summary>Error report</summary>

> /Users/andrej/code/{PROJECT}/node_modules/braintree/index.js
> 
> /Users/andrej/code/{PROJECT}/node_modules/braintree/lib/braintree.js
> An error occurred while trying to read the map file at /Users/andrej/code/{PROJECT}/node_modules/braintree/lib/braintree.map
> Error: ENOENT: no such file or directory, open '/Users/andrej/code/{PROJECT}/node_modules/braintree/lib/braintree.map'readFromFileMap @ index.js:32Converter @ index.js:39exports.fromMapFileComment @ index.js:112devtoolWrapModule @ require-hook.js:75Module._compile @ module.js:526devtoolCompileModule @ require-hook.js:32Module.load @ module.js:473tryModuleLoad @ module.js:432Module._load @ module.js:424require @ internal/module.js:20(anonymous function) @ index.js [sm]:3Module._compile @ module.js:556devtoolCompileModule @ require-hook.js:32Module.load @ module.js:473tryModuleLoad @ module.js:432Module._load @ module.js:424require @ internal/module.js:20(anonymous function) @ index.js [sm]:1Module._compile @ module.js:556devtoolCompileModule @ require-hook.js:32Module.load @ module.js:473tryModuleLoad @ module.js:432Module._load @ module.js:424require @ internal/module.js:20(anonymous function) @ jwt.js [sm]:2Module._compile @ module.js:556devtoolCompileModule @ require-hook.js:32Module.load @ module.js:473tryModuleLoad @ module.js:432Module._load @ module.js:424require @ internal/module.js:20(anonymous function) @ jwt.js [sm]:1Module._compile @ module.js:556devtoolCompileModule @ require-hook.js:32Module.load @ module.js:473tryModuleLoad @ module.js:432Module._load @ module.js:424require @ internal/module.js:20(anonymous function) @ index.js [sm]:2Module._compile @ module.js:556devtoolCompileModule @ require-hook.js:32Module.load @ module.js:473tryModuleLoad @ module.js:432Module._load @ module.js:424require @ internal/module.js:20(anonymous function) @ index.js [sm]:5Module._compile @ module.js:556devtoolCompileModule @ require-hook.js:32Module.load @ module.js:473tryModuleLoad @ module.js:432Module._load @ module.js:424require @ internal/module.js:20(anonymous function) @ preload.js:88emitOne @ events.js:96emit @ events.js:188
> VM307:1 '//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.

</details>

**Comment by crookedneighbor** [comment]
V2.0.0, which we just released, drops the dependency on coffeescript, so you shouldn't need to deal with sourcemaps at all.

**Comment by Andreyco** [comment]
That was... quick! Thank you
