### ISSUE TITLE
Error: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by vinothmoorthkumar** [braintree/braintree_node#93]
Hi,
   I m getting this error from braintree package while payment process. Pls Help

**Comment by danakatz** [comment]
Hi @vinothmoorthkumar, we'll need some more information to figure out what's going on here. I'd suggest reaching out to [Braintree support](mailto:support@braintreepayments.com) for help debugging the specifics of your integration.

**Comment by vinothmoorthkumar** [comment]
Hi,

var transaction = {
        'amount': order.total,
        'creditCard': {
            'number': 41111111111111111
            'expirationMonth': 10,
            'expirationYear': 2017,
            'cvv': 123
        },
        'customer': {
            'firstName': vinoth,
            'email': vinoth@gmail.com,
        },                                                                                       
    options: {
        submitForSettlement: true
    }
};
gateway.transaction.sale(transaction,
    function (err, result) {

});

**Comment by crookedneighbor** [comment]
@vinothmoorthkumar The problem is more likely to do with your server than with the code. Please email support@braintreepayments.com with the details of your integration for help troubleshooting this issue.
