### ISSUE TITLE
SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by infacq** [braintree/braintree_node#94]
I use the lastest version on a meteor project and I hit this error when run meteor

```bash
let version = require('../package.json').version;
```

my Node version is `6.3.1` and NPM is `3.9.5`. Any Idea what could cause this

**Comment by crookedneighbor** [comment]
Could you provide a github repo that reproduces the problem?

**Comment by infacq** [comment]
My meteor project is quite simple and you can produce the error when you're using npm to require this library

**Comment by crookedneighbor** [comment]
I don't use meteor, but with this basic node code, it works fine for me.


```js
var braintree = require('braintree');
var gateway = braintree.connect({
  environment:  braintree.Environment.Sandbox,
  merchantId:   'id',
  publicKey:    'key',
  privateKey:   'key'
});

gateway.clientToken.generate({}, function (err, response) {
    var clientToken = response.clientToken
    console.log(clientToken)
});
```

**Comment by infacq** [comment]
that's the problem. It only say `SyntaxError: Unexpected strict mode reserved word`. Wonder what hacks to overcome this

**Comment by crookedneighbor** [comment]
I have a sample meteor app set up and I'm not getting that error: https://github.com/crookedneighbor/braintree-meteor-without-use-strict-error/blob/master/server/main.js

**Comment by crookedneighbor** [comment]
I don't think this has anything to do with the braintree library, but if you can provide a reproducible example for me, I'm happy to troubleshoot further.
