### ISSUE TITLE
Is there a server-side equiv for obtaining a nonce w/o customer ID?

### ISSUE THREAD

**Issue by theogravity** [braintree/braintree_node#96]
I have a situation where I have custom test cards that generate specific responses with the merchant endpoint I'm using (via the Forward API). These test cards shouldn't be associated to a customer/customer ID.

As a hack, I'm including the braintree web client on the server-side (on node with jsdom to get proper emulation of XMLHttpRequest that braintree-web requires, which is not ideal).

Is there an equiv to this?

https://github.com/braintree/braintree-web#advanced-integration

**Comment by bluk** [comment]
Since it seems you have a unique custom test scenario, please contact [Braintree support](https://articles.braintreepayments.com) at the bottom of the linked page.
