### ISSUE TITLE
Add ability to inject stubbed payloads into sampleNotifications

### ISSUE THREAD

**Issue by gregsochanik** [braintree/braintree_node#97]
I use the `sampleNotifications` function in the WebhookTestingGateway https://developers.braintreepayments.com/guides/webhooks/testing-go-live/node, which are great, but I've noticed that the `subjectXmlForSubscription` contains no data, which makes it difficult to test for specific scenarios.

https://github.com/braintree/braintree_node/blob/master/lib/braintree/webhook_testing_gateway.js#L251

What would be excellent, is if there was an option to inject stub payloads into the sampleNotification method. They could either be xml, or even go a step further allow injection of a javascript object, which would then need to be converted into xml.

This would mean a developer could easily set up a suite of unit test for specific scenarios and would be a massive help when integrating.

e.g. instead of 

``` javascript
const sampleNotification = gateway.webhookTesting.sampleNotification(
  braintree.WebhookNotification.Kind.SubscriptionWentPastDue,
  "myId"
);
```

Something like:

``` javascript
const stubbedPayload = {
    kind: 'subscription_created',
    timestamp: '2017-03-14T15:47:33Z',
    subject: {
      subscription: {
        billingPeriodEndDate: '2017-03-21',
        billingPeriodStartDate: '2017-03-14',
        paidThroughDate: '2017-03-21',
        price: '19.99',
        status: 'Trialing',
        trialPeriod: true,
        transactions: [
          {
            currencyIsoCode: 'USD',
            customer: { id: 'my-user-id' }
          }
        ]
      }
    }
};
const sampleNotification = gateway.webhookTesting.sampleNotification(
  braintree.WebhookNotification.Kind.SubscriptionWentActive,
  stubbedPayload
);
```

**Comment by sdcoffey** [comment]
Hey @gregsochanik,

Sorry for taking so long to get back with you. I think this is a great idea. I’ll talk with our team and discuss how to prioritize this work across SDKs. In the meantime, if you’d like to take a stab at this yourself, feel free to submit a PR.

**Comment by gregsochanik** [comment]
Sure - although I'm a bit snowed under with other stuff at the mo, but I'll try and put something together. I've already built a version in my service's test suite to allow me to do it, so should just be a case of porting it to this library. 

Will let you know.

**Comment by jthegedus** [comment]
Any planned release for this feature @sdcoffey? If you're still too busy @gregsochanik I could make a PR and deal with the nuances of getting it merged, your existing implementation would speed this process up though. Any chance you could dump the code here?

**Comment by jthegedus** [comment]
PR open!

**Comment by gregsochanik** [comment]
@jthegedus That would be great! I'll pull out what code I can and dump it in a gist, then you can take it from there.

**Comment by gregsochanik** [comment]
Ahh, just spotted the PR, will take a look at that and compare it to what I've done.

**Comment by gregsochanik** [comment]
@jthegedus TBH it looks like you've pretty much done what I have done, in fact you've gone one step further and used `js2xmlparser`, where I've only been using raw XML. So :+1:

**Comment by jthegedus** [comment]
@gregsochanik Thanks for having a look. It differs from the existing methods in that you must pass the Kind within the payload itself as this then allows the sending of additional payload information that is not a child of the <subject> element, as in the production webhook payloads. Hopefully, this gets merged soon.

**Comment by gregsochanik** [comment]
Ahh - OK. I was still separating the kind from the payload and then forming the xmlEnvelope in a separate method, i.e:

``` javascript

function xmlEnvelope (eventKind, sampleXml) {
  return `<notification>
      <timestamp type="datetime">${dateFormat(new Date(), dateFormat.masks.isoUtcDateTime, true)}</timestamp>
      <kind>${eventKind}</kind>
      <subject>
        ${sampleXml}
      </subject>
    </notification>`;
}

```

and then base64-ing that to create the signature.

**Comment by jthegedus** [comment]
I initially implemented it that way, but quickly found using the Braintree production webhook responses would throw errors because of the attributes after the <subject> element. EG:
```js
{
   timestamp:dateFormat(new Date(), dateFormat.masks.isoUtcDateTime, true),
   kind:WebhookNotification.Kind.SubscriptionChargedSuccessfully,
   subject:{
      subscription:{
         id:'mySubscription',
         transactions:[
            {
               status:'submitted_for_settlement',
               amount:'49.99'
            }
         ],
         addOns:[ ],
         discounts:[ ]
      }
   },
   subscription:{
      id:'mySubscription',
      transactions:[
         {
            status:'submitted_for_settlement',
            amount:'49.99',
            creditCard:{
               maskedNumber:'undefined******undefined',
               expirationDate:'undefined/undefined'
            },
            paypalAccount:{ },
            coinbaseAccount:{ },
            applePayCard:{ },
            androidPayCard:{ },
            disbursementDetails:{ },
            visaCheckoutCard:{ },
            masterpassCard:{ }
         }
      ],
      addOns:[ ],
      discounts:[ ]
   }
};
```

The accounts information is separated into this second part and it's not clear without running the webhooks what the true response format will be (as the testing ones are not complete).

Feedback from the Braintree team will help clarify what's necessary and maybe it'll change back to the split method. Time will tell.

**Comment by crookedneighbor** [comment]
We're not going to add this feature at this time. (See https://github.com/braintree/braintree_node/pull/111#issuecomment-356122013)
