### ISSUE TITLE
braintree/http.js _aborted flag should be local variable and not member variable

### ISSUE THREAD

**Issue by devendrawani** [braintree/braintree_node#99]
once _aborted flag is set to true on timeout (http.js#L116), subsequent http errors are failing to reach callback (http.js#L131) causing infinite wait at callers end.

Steps to reproduce
1. Initialise braintree => gatway = braintree.connect(config)
2. Do search query => stream = gateway.transaction.search(...)
3. Disconnect internet, and let request timeout
4. stream.on('error') handler will be called. 
5. Re attempt gateway.transaction.search(...).
6. Disconnect internet, and let request timeout
7. stream.on('error') handler will be never called.

**Comment by crookedneighbor** [comment]
Thanks for reporting this. Do you want to open a PR?

**Comment by crookedneighbor** [comment]
I've worked on a fix for this. It'll likely go out in the next release. I'll update this issue when it does.

**Comment by crookedneighbor** [comment]
This is fixed in 2.1.1. Thanks for reporting it!
